### ISSUE TITLE
Did we just lose all issues/bug reports etc?

### ISSUE THREAD

**Issue by jonasskafte** [awesomemotive/WP-Mail-SMTP#1]
Hi there,

Hope you are well!

Did we just lose all issues submitted or have you just started afresh here on GitHub and kept the bug reports elsewhere?

Just asking because if we've lost all the issues then I'll re-add mine.

Cheers!

**Comment by slaFFik** [comment]
Hi @jonasskafte 

No, we haven't lost anything, we decided to use this repo for publicly submitted issues and for hosting the release-ready versions of the WP Mail SMTP plugin.
All issues are safe and will be processed accordingly.

I see your report about WC emails on a Multisite install, so nothing for you to worry about.

**Comment by jonasskafte** [comment]
Hi there @slaFFik (CC: @jaredatch)

Hope you are both well and thanks for your latest update to 1.3.0!

I've read the changelog for the update, but I couldn't immediately see anything about this issue – could you possibly confirm whether or not we can expect a fix to this in this version, or if we should hold on with reactivating the plugin (I've got it deactivated until it works on multisite installations as well).

Many thanks!!

**Comment by slaFFik** [comment]
Hi,

We haven't done anything specifically for WC or MultiSite. 
But we did big improvements in 1.3.0, so you can test that.

**Comment by jonasskafte** [comment]
Hi there @slaFFik, 

Thanks for responding to this!

I've done some tests now and unfortunately the problem persists also after updating to 1.3.0.

I'm wondering if you could possibly re-add the original issue I had posted about this, so that I won't have to add it again? Do you still have access to the issues that have been removed somewhere? I'm thinking that since it still a problem and since it wasn't fixed in the latest release, that it should ideally be added again to the list.

Many thanks!

**Comment by slaFFik** [comment]
No need to duplicate issues, we still have everything, just in another repo. The current plan to have this fixed in 1.4.0, no ETA though.

**Comment by jonasskafte** [comment]
Hi @slaFFik,

Thanks for the update. In that case, I think I'll look at using another SMTP plugin as it's crucial to us that this part of the plugin is working correctly – and we need it working as soon as possible as we were hoping that it would have been fixed in 1.3.0. We cannot wait any longer I'm afraid. I am aware that this is a free plugin and so we cannot expect anything, really, which is also why I'm going to look at other options instead of bothering you anymore... But please do let me know if you one day release a fix for this – then I might just come back to WP Mail SMTP! 🙂

Thanks for your responses and good luck with the further development of this great plugin!

**Comment by slaFFik** [comment]
Thank you and good luck to you too!
