### ISSUE TITLE
Configurable "FROM" email in a multisite install 

### ISSUE THREAD

**Issue by brickcap** [awesomemotive/wp-mail-smtp#10]
Hi Callum,

Thanks for making this plugin! Is it possible to configure the FROM email in a multisite install? I want to use this plugin with [wp-email-subscribers](https://wordpress.org/plugins/email-subscribers/) such that every website owner in a multisite network could submit his own FROM email. 

As it is wp-mail-smtp requires you to have a global FROM email that is configured once. How would that conflict with this requirement? Could you let me know what changes would I need to make in the code, if any, to make this work? 

Thanks,
Akshat

**Comment by slaFFik** [comment]
This already can be achieved using WP hooks.
The main logic - find a hook that fires when a new site created, it has a `$blog_id`. Use `update_site_option()` to save into the database a new required values for required fields. Thus defaults will be present and can be based on site admin_email and description.

**Comment by brickcap** [comment]
Thank you @slaFFik for your response! Your idea is good. However is there any alternative if I don't want to touch my database. Specifically I wanted to know if it is possible to adjust the FROM email just before it is sent via wp_smtp? In other words is there a hook in wp_smtp itself? I'm asking because there is a possibility that I may want to use a different email than the one supplied as site-admin. And so if wp_smtp provided a hook the setup could be more dynamic. 

Please also let me know if it would be better/more straightforward if I simply hooked the `update_site_option()` as you suggested.  

If it would help I also asked this question on the [email subscribers forum](https://wordpress.org/support/topic/from-name-in-a-multisite-install-with-an-smtp-plugin/?view=all). 

Many thanks,
Akshat

**Comment by slaFFik** [comment]
No, it's not possible. You should use either constant or database value. Constant will be global for all subsites, so the only way is to modify DB option when the subsite is created.

**Comment by brickcap** [comment]
All right @slaFFik thanks once more!

**Comment by slaFFik** [comment]
Closing this issue in favor of #100.
