### ISSUE TITLE
Subscribe Emails in Word press - generated by the WP Mail SMTP WordPress plugin

### ISSUE THREAD

**Issue by mrmstevenson** [awesomemotive/wp-mail-smtp#108]
## Plugin version 
1.2.1

## Current Behavior

When I subscribe to Blog using Jetpack the confirmation email says
"generated by the WP Mail SMTP WordPress plugin" and no confirmation button ?

## Expected Behavior

Confirmation email as this article suggests 
https://beginnerblogging.net/jetpack-email-subscriptions/

## Steps to Reproduce (for bugs)

1. Open my page http://stepstorecovery.co.uk/ fill in email in subscribe in footer
2. Email delivers with text "This email was sent by Other SMTP mailer, and generated by the WP Mail SMTP WordPress plugin."
3.
4.

**Comment by slaFFik** [comment]
Here is a screenshot of an email that I got: http://cloud.supportally.com/oZ5Z
All is good so far.
