### ISSUE TITLE
Cannot send mail | Gmail account | token decode - json error

### ISSUE THREAD

**Issue by cyph3rgr** [awesomemotive/WP-Mail-SMTP#11]
Hello,

I face a problem with WPMail SMTP and Google Analytics Pro plugin.
When Analytics plugin is enabled, no mails are sent. After deactivating Analytics plugin everything works as expected. No errors and mails are sent normally.

> Versions:
> WordPress: 4.9.6
> WordPress MS: No
> PHP: 7.2.6
> WP Mail SMTP: 1.2.5
> 
> Params:
> Mailer: gmail
> Constants: No
> 
> Debug:
> There was a problem while retrieving Mailer for gmail: Could not json decode the token

I found out [here ](https://wordpress.org/support/topic/error-when-authorizing-plugin-from-settings-page/page/2/#post-10432071)that you already know of the bug and is related to API classes names.
Can you please tell me how did you managed to solve the issue?
It is mentioned that in the upcoming 1.3.0 release the problem will be fixed.. Should I wait for the update to be released? Can you approximatelly estimate when 1.3.0 version will be out?

Regards, Othon

## Steps to Reproduce (for bugs)

1. Install and Enable _WPMail SMTP 1.2.5_
2. Install and enable _WooCommerce Google Analytics Pro 1.5.1_
3. Test mail & all other mail functions stop working

**Comment by jaredatch** [comment]
This should be resolved in our next update (1.3) which hopefully is going out tomorrow 😎

**Comment by cyph3rgr** [comment]
Thank you for your reply Mr. Jared. Hopefully everything will work normally again!
