### ISSUE TITLE
Disable settings inputs when options are defined in config file

### ISSUE THREAD

**Issue by thomasfw** [awesomemotive/wp-mail-smtp#112]
**1.2.2**

## Current Behavior
When we set our WPMS options through our config file (e.g. `WPMS_MAILGUN_API_KEY`, `WPMS_MAILGUN_DOMAIN`), we still have the option to set these through the input in _Settings > WP Mail SMTP_. I'm not sure if this is intended or has just been overlooked, but it's pretty confusing.

## Expected Behavior
Disable and fill inputs with a placeholder so it's obvious that the options have been set elsewhere.

**Comment by thomasfw** [comment]
I see that I just needed to define `WPMS_ON`. Is this documented?

**Comment by lkraav** [comment]
@thomasfw constants are very badly documented right now. I had to grep the source to find the list and go off of that. I'm sure it'll improve soon enough as the plugin gains popularity under the @awesomemotive umbrella.
