### ISSUE TITLE
Guzzlehttp/psr7 Security update

### ISSUE THREAD

**Issue by davis2125** [awesomemotive/WP-Mail-SMTP#115]
The plugin is using a dependency of guzzle which has a recent security issue. Is it possible to get this updated?

https://github.com/guzzle/psr7/security/advisories/GHSA-q7rv-6hp3-vh96

**Comment by capuderg** [comment]
Hi @davis2125,

we are planning on a plugin update soon, and the version of guzzlehttp/psr7 will be updated to 1.8.5.

Thanks for letting us know and take care!
