### ISSUE TITLE
Constants not working after save

### ISSUE THREAD

**Issue by Naoell** [awesomemotive/wp-mail-smtp#116]
I discovered a bug when using constants. 

On save the plugin creates a record in the database, which overrides the constants. 
After this the plugin starts using default values, and mail sendings fail.

Plugin ver.: 1.2.2
WP ver.: 4.9.1
PHP ver.: 7.1.18
Web Server: Windows Server 2016 and IIS 10 

Steps to reproduce
1.) Setup site

2.) Add constants in an mu-plugin plugin.

3.) Install WP Mail SMTP

4.) Navigate to the WP Mail SMTP and click "Save".

---

Deleting the row in wp_options with option_name = 'wp_mail_smtp', makes the constants work again.

**Comment by slaFFik** [comment]
Closing this issue in favor of #90.
