### ISSUE TITLE
Can't enter From email in WP Mail SMTP settings

### ISSUE THREAD

**Issue by pgaov** [awesomemotive/WP-Mail-SMTP#117]
## Expected Behavior

Should be able to enter the From email account.

## Current Behavior

Can't enter anything in the field. There's a message there saying something about authenticating the email first. I'm trying to set the plugin up to work with Gmail and I'm following the instructions from the plugin website for the Google setup.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by capuderg** [comment]
Hi,

we replied to you in the WP Mail SMTP support thread: https://wordpress.org/support/topic/problems-setting-up-wp-mail-smtp/

If you have further questions, please respond in that support thread.

Have a nice day!
