### ISSUE TITLE
Need to strip slashes in "From Name" field

### ISSUE THREAD

**Issue by blogtutor** [awesomemotive/wp-mail-smtp#118]
## Plugin version 
1.2.2

## Current Behavior

When saving a "From" name that uses an apostrophe, a backslash is added before the apostrophe.

For example, `Andrew's Blog` shows up as `Andrew\'s Blog` after saving. It also shows up with the slash in the actual emails that are sent.

## Expected Behavior

The "From Name" shouldn't have a slash in it.  ;)

## Possible Solution

Strip slashes!

## Steps to Reproduce (for bugs)

1. Enter a "From Name" with an apostrophe, such as "Andrew's Blog"
2.  Click "Save Settings"
3. Look at the From Name field again.

**Comment by pandymic** [comment]
Just a quick note that this appears to apply to all of the serialized data in the option value, including SMTP usernames.

Current work-around is to hard-code the exact desired values by defining them as WPMS_* constants.

- WPMS_MAIL_FROM_NAME
- WPMS_SMTP_USER
- WPMS_SMTP_PASS
- etc.

**Comment by pandymic** [comment]
Just to further expand on this, it would appear that strings which contain sets of characters that could be interpreted as URL-encoded values are also behaving oddly.

Including any three character sequence that begins with a percent symbol (%) and is proceeded by two characters that evaluate to HEX values (a-f, 0-9) is stripped from the string when serialized and stored in the database.

For example, the string:

> abc123f

As expected the above is stored in the options database as you see it. It's serialized as part of the wp_mail_smtp option and the segment looks like this:

> s:7:"abc123f"

However, if you save the following string:

> abc12%3f

it becomes:

> s:5:"abc12"

Interestingly, I expected it to perform some kind of URL-decode and convert the %3f value to it's HTML entity equivalent. In this case, a question mark (?) Instead, however, it simply drops the entire segment from the string.

**Comment by pandymic** [comment]
So after some quick digging I think I've gotten to the bottom of the issue.

./src/[Options.php](https://github.com/awesomemotive/wp-mail-smtp/blob/master/src/Options.php)
> [Line 455](https://github.com/awesomemotive/wp-mail-smtp/blob/master/src/Options.php#L455)
> [Line 489](https://github.com/awesomemotive/wp-mail-smtp/blob/master/src/Options.php#L489)
> [Line 495](https://github.com/awesomemotive/wp-mail-smtp/blob/master/src/Options.php#L495)

Per the WordPress developer documentation, the [sanitize_text_field()](https://developer.wordpress.org/reference/functions/sanitize_text_field/) function strips octets. This would explain why the series of characters are disappearing outright prior to being serialized. I'd recommend perhaps sanitizing the string using a less restrictive function. There's potential for further issues as this particular function does some other nasty stuff to string values. Again, per the documentation:

> - Checks for invalid UTF-8,
> - Converts single < characters to entities
> - Strips all tags
> - Removes line breaks, tabs, and extra whitespace
> - Strips octets

Many of which are very valid and oft encouraged elements in a strong password.

**Comment by pandymic** [comment]
I see that there's already a closed issue (#74) on the topic of sanitize_text_field() as well as a merged pull request (#77)

These appear to have been made for the 1.1.0 milestone but they're not present in the current master or develop branches.

It's 2:30am and I'm scratching my head. Am I missing something? Maybe it's time to call it a night and look at it again with fresh eyes.

Keep up the great work.

**Comment by slaFFik** [comment]
@blogtutor

I've added stripslashes.

@pandymic 

Great insights, I'm currently testing `wp_strip_all_tags( $value, true )` that also removes new lines (just in case).
