### ISSUE TITLE
Not Able to Change from

### ISSUE THREAD

**Issue by rahulr225** [awesomemotive/WP-Mail-SMTP#118]
## Expected Behavior

I have installed the plugin and do all the setting properly.
I have 3 form in which I need to send auto emailer to User who fill the form but I also need to change the reply to and from email recipient. It is taking forcefully I have unchecked the  force email address also.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by capuderg** [comment]
Hi @rahulr225,

please open a support thread here: https://wordpress.org/support/plugin/wp-mail-smtp/

Our support staff will help you out with any configuration issues you might have.

Take care!
