### ISSUE TITLE
Latest update is broken on PHP 5.3.2

### ISSUE THREAD

**Issue by corelanc0d3r** [awesomemotive/WP-Mail-SMTP#12]
## Current Behavior
PHP errors, wordpress site not loading
[Fri Jun 29 08:57:03 2018] [error] [client A.B.C.D] PHP Parse error:  syntax error, unexpected '[' in /web/wp-content/plugins/wp-mail-smtp/vendor/guzzlehttp/psr7/src/functions.php on line 78

**Comment by slaFFik** [comment]
Thanks for report, @corelanc0d3r 
Working on it, will be fixed in 1.3.1 due today.

**Comment by slaFFik** [comment]
But please, upgrade your PHP version :) 

https://wordpress.org/support/topic/new-error-with-todays-update/#post-10446331
