### ISSUE TITLE
Unable to change the smtp password in WP Mail SMTP Wordpress Plugin

### ISSUE THREAD

**Issue by deepakshah13** [awesomemotive/wp-mail-smtp#120]
## Current Issue/Bug
I have installed WP Mail SMTP Plugin (By WPForms author)  in WordPress (Version 4.9.1). I had added smtp username and password earlier. Now I am trying to change old entries but unable to change smtp password. SMTP Password field is disabled,
I am requesting to help me in this regard.

Thanks.

**Comment by slaFFik** [comment]
Remove or disable values redeclaring in `wp-config.php` in constants like `WPMS_SMTP_PASS`.
