### ISSUE TITLE
reset password email changing to charset=”ascii”

### ISSUE THREAD

**Issue by napa-web-designer** [awesomemotive/wp-mail-smtp#121]
## Plugin version 

1.2.2

## SUMMARY
Using Mailgun through your plugin seems to change the email to Content-Type: text/html; charset=”ascii” which results in a password reset email that is unformatted and does not show the actual link to click to reset password.

## DETAILS
After installing your plugin and using Mailgun successfully for many emails being sent out, when I or anyone on my site clicks the link on the login page to reset their password, the resulting email comes unformatted (no paragraph breaks) and the link is not there. I changed the option in your plugin to use the PHP Mailer and the emails were properly formatted and the links there.

I looked at the Raw Source of both emails and could see that the content of the email was exactly the same for both messages with a number of differences in the code part at the top, however what stuck out to me at least was that in the email that did show a proper email content it had:

Content-Type: text/plain; charset=UTF-8

and for the one generated using Mailgun setting in your plugin generated:

Content-Type: text/html; charset=”ascii”

Which I figured was the likely reason.

## Steps to Reproduce (for bugs)
1. With Mailgun working on your plugin, use the reset password link on your login page
2. Check the email that is sent.

[email works.rtf.zip](https://github.com/awesomemotive/wp-mail-smtp/files/1633295/email.works.rtf.zip)
[email no work.rtf.zip](https://github.com/awesomemotive/wp-mail-smtp/files/1633296/email.no.work.rtf.zip)

![screen shot 2018-01-15 at 4 50 08 pm](https://user-images.githubusercontent.com/1827904/34966935-5916d216-fa14-11e7-8f2a-64538cc9b7b8.jpg)

**Comment by slaFFik** [comment]
That's strange, but I will check this out. 
Thanks for reporting!

**Comment by napa-web-designer** [comment]
were you able to replicate?

**Comment by jaredatch** [comment]
Related to #101 and #125. Closing this so we can continue discussion on the matter in #101.

Should fix in an upcoming release. Bottom line is WP core emails are plaintext and need to be sent out as plaintext, not HTML.

**Comment by napa-web-designer** [comment]
When do you think this will be resolved. It is kind of a crucial issue.
