### ISSUE TITLE
Call to undefined method WPMailSMTP\Core::get_connections_manager()

### ISSUE THREAD

**Issue by nexbridge** [awesomemotive/WP-Mail-SMTP#122]
OS: Debian 10.12
Wordpress version: 6.0
Plugin version: WP Mail SMTP Lite 3.7.0

I'm not sure how to replicate the issue, but please see below for a stack trace, which will hopefully give you the information that you need:

> [2022-12-15 22:30:04] Call to undefined method WPMailSMTP\Core::get_connections_manager()
Error at /wp-content/plugins/wp-mail-smtp/src/Providers/MailerAbstract.php(129):
#0 /wp-content/plugins/wp-mail-smtp/src/Providers/Sendgrid/Mailer.php(47): WPMailSMTP\Providers\MailerAbstract->__construct(Object(WPMailSMTP\MailCatcherV6), NULL)
#1 /wp-content/plugins/wp-mail-smtp/src/Providers/Loader.php(193): WPMailSMTP\Providers\Sendgrid\Mailer->__construct(Object(WPMailSMTP\MailCatcherV6), NULL)
#2 /wp-content/plugins/wp-mail-smtp/src/Providers/Loader.php(148): WPMailSMTP\Providers\Loader->get_entity('sendgrid', 'Mailer', Array)
#3 /wp-content/plugins/wp-mail-smtp/src/MailCatcherV6.php(237): WPMailSMTP\Providers\Loader->get_mailer('sendgrid', Object(WPMailSMTP\MailCatcherV6))
#4 /wp-includes/pluggable.php(548): WPMailSMTP\MailCatcherV6->send()
#5 /wp-content/plugins/stops-core-theme-and-plugin-updates/includes/MPSUM_Send_Email_Notifications.php(193): wp_mail(Array, '[REDACTED] Backgro...', 'WordPress site:...', Array)
#6 /wp-includes/class-wp-hook.php(307): MPSUM_Send_Email_Notifications->send_notification_emails(Array)
#7 /wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#8 /wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#9 /wp-admin/includes/class-wp-automatic-updater.php(558): do_action('automatic_updat...', Array)
#10 /wp-includes/update.php(726): WP_Automatic_Updater->run()
#11 /wp-includes/class-wp-hook.php(307): wp_maybe_auto_update('')
#12 /wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#13 /wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#14 /wp-content/plugins/stops-core-theme-and-plugin-updates/includes/MPSUM_Disable_Updates.php(191): do_action('wp_maybe_auto_u...')
#15 /wp-includes/class-wp-hook.php(307): MPSUM_Disable_Updates->maybe_auto_update()
#16 /wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#17 /wp-includes/plugin.php(524): WP_Hook->do_action(Array)
#18 /wp-cron.php(138): do_action_ref_array('wp_update_plugi...', Array)
#19 {main}

**Comment by capuderg** [comment]
Hi @nexbridge,

the method in question `WPMailSMTP\Core::get_connections_manager` is definitely present/defined in the 3.7.0 release. So I think there are two possible reasons for this error:
- maybe your update/install did not finish completely and the src/Core.php file was not updated correctly. Could you please re-install the plugin and see if that will resolve your issue?
- are you using caching? OPCache to be exact. Maybe some of the code is cached from the previous version and that's why the error occurs. If you are using OPCache, please clear the cache and see if that will resolve your issue.

Let me know how it goes.

**Comment by nexbridge** [comment]
OK thanks - emails have been working fine since I'll probably just keep an eye on it to see if it happens again. I suspect that it may have been a timing issue when the plugin was updating, i.e. that it was trying to send an email to notify that the plugin had been updated when the plugin wasn't quite ready to start sending email again.
