### ISSUE TITLE
Can not load textdomain file in php7

### ISSUE THREAD

**Issue by bestony** [awesomemotive/wp-mail-smtp#123]
Can not load textdomain file in php7
## Plugin version 
1.2.2
## Current Behavior
load english for user who use chinese
## Expected Behavior
load Chinese for user who use chinese
## Possible Solution

add load text domain code

**Comment by slaFFik** [comment]
Put a generated translated file in `/wp-content/languages/plugins/wp-mail-smtp.mo`. Or better submit to https://translate.wordpress.org/projects/wp-plugins/wp-mail-smtp

**Comment by slaFFik** [comment]
@bestony 
I will include in 1.2.5 the fix to properly load the translation file from plugin language directory. More details in a linked PR (which I will close for reasons that will be described there).
