### ISSUE TITLE
Automatic conversion of false to array is deprecated

### ISSUE THREAD

**Issue by ve3** [awesomemotive/WP-Mail-SMTP#123]
## Expected Behavior

No errors on plugins  management page. ( /wp-admin/plugins.php?plugin_status=all&paged=1&s )

## Current Behavior

Showing error: 

> Automatic conversion of false to array is deprecated in wp-mail-smtp\src\WP.php on line 570

This is deprecated error since PHP 8.1.  
The error message appears once for few minutes, not every reload. Looks like this happens when WordPress checking for the update.

## Steps to Reproduce

1. Install WordPress 6.1.1 or beta tester 6.2-alpha-nnnn (where nnnn is number). Use PHP 8.1 or newer.
2. Go to WordPress admin dashboard.
3. Go to plugins management page.
4. Error occur.

**Comment by capuderg** [comment]
Thank you for opening this issue!

We'll try to resolve this in one of our future updates.

**Comment by alexander-sakal** [comment]
Hello @ve3. This issue was resolved in v.3.8.0. Thanks for the report!
