### ISSUE TITLE
Password Reset Email sent via Mailgun API doesn't include links

### ISSUE THREAD

**Issue by blogtutor** [awesomemotive/wp-mail-smtp#125]
## Plugin version 
1.2.2

## Current Behavior
When Mailgun is configured with the API, the WordPress password reset email is sent with the link stripped out.  If you view the message details in the Mailgun logs, it shows the correct email, with line breaks and the reset link. But in Gmail and iPhone Mail, the message shows up with no linebreaks and no URLs - just a row of text.  However, if you do "Show Original" in Gmail it does show the correct info.

I've now encountered this on two different sites.

## Expected Behavior
It should send an email with linebreaks and the password reset link.

## Steps to Reproduce (for bugs)
1. Configure the plugin to send via Mailgun API.
2. Log out, and go to /wp-login.php?action=lostpassword
3. Send a password reset email, then view it in Gmail or on iPhone mail.

## Workaround
Send through Mailgun via SMTP - that works fine.

## Screenshots (if appropriate)
Inside Gmail: https://cl.ly/orEg
If I click "Show Original" in Gmail it gives me this: https://cl.ly/osKH

**Comment by jaredatch** [comment]
Related to #101.

Right now we always send emails in HTML, no exceptions.

This causes issues with some of the WP core emails, since all core emails are sent plain text.

What we'll try to do in an upcoming update is detect the type of email by inspecting the `headers` sent to `wp_mail`. If HTML, will send HTML, otherwise send as plain text. This, I believe, should resolve the issue.

**Comment by jaredatch** [comment]
Closing as we can continue discussion in #101.

**Comment by blogtutor** [comment]
@jaredatch However, the email comes through just fine when sending via Mailgun/SMTP rather than Mailgun/API.  So when you say "no exceptions" are you just talking about the Mailgun API?

**Comment by slaFFik** [comment]
Mailgun/SMTP is using bundled `PHPMailer` class in WordPress, so all its settings, including headers for `plain/text` or `text/html` email is taken into consideration.

Mailgun/API always sends using `text/html`, regardless of the initial header, generated as `plain/text` by default WP emails (like reset email).

So we will adjust the logic to be smarter and check the corresponding header before reapplying it.
