### ISSUE TITLE
Multisite: emails are not processed by plugin

### ISSUE THREAD

**Issue by rlankhorst** [awesomemotive/wp-mail-smtp#126]
## Plugin version 
upgrading from 0.11.1 to 1.2.1 results in issue

## Current Behavior
After upgrading from 0.11.1 to 1.2.1 a reset password action on a subsite results in the following error message:

**The e-mail could not be sent.Possible reason: your host may have disabled the mail() function...**

We use multisite, with the variables defined in constants in the wp-config.php. 

When debugging, it seems the WP MAIL SMTP phpmailer_init_smtp action is not executed at all. The phpmailer_init_smtp function does not seem to get instantiated. 

I see some new code, spl_autoload_register, is it possible this is causing the plugin code not to get loaded in case of WordPress multisite setups?

## Steps to Reproduce
1. Install WordPress with multisite
2. Network activate WP MAIL SMTP plugin
3. Use constants to define the SMTP settings (I don't think this is related, but just in case)
4. Try to reset the password. You will see the message. 

Roll back to 0.11.1: message is gone, mailing works.

**Comment by slaFFik** [comment]
> The e-mail could not be sent. Possible reason: your host may have disabled the mail() function...

WP Mail SMTP plugin does not generate this error. It may be generated by other SMTP-related plugins and other plugins, like RCP (Pro) (from the recent experience).

> I see some new code, spl_autoload_register, is it possible this is causing the plugin code not to get loaded in case of WordPress multisite setups?

Depends on your PHP version, you have not provided the debug output, so I can't say for sure. 
If you are still using PHP 5.2 - the whole plugin will load the old version, as of 0.11.2. If you are on a newer version - you will see a new admin area with new mailers. In that case, if there were problems with `spl_autoload_register()` you would have a bunch of fatals and a broken site/plugin. So I would answer your question as No. We also have confirmations from other users that the plugin works for them on WordPress Multisite.

**Comment by rlankhorst** [comment]
Thanks for your response. The site runs on PHP 7, NGINX, WP 4.9

I know the error message is not from the plugin: it's a message from WordPress itself, located in wp-login.php. I posted it because the message is the result of the wp_mail() function failing, because of the update to 1.2.1.

The cause of the problem has nothing to do with email itself: the issue is that the plugin code is not executing at all, which results in the settings not being initialized on the phpmailer object.

The password reset works on 0.11.1, but not on the latest version. Downgrading fixes the issue, which seems to confirm that the issue is caused by the update, and that the email settings are correct. 

Other emails are getting sent without any probems with both versions, like for example the test email. It's only the password reset mail that does not run. Possibly the new function causes the phpmailer_init_smtp to be added after the password reset function has run. 

With 0.11.1 the wp_mail_smtp.php is executed, adding the action to initialize the settings on the phpmailer object, and the email gets sent. 

In the current version the wp_mail_smtp.php file does not run, so the phpmailer_init_smtp function is never executed, causing the settings not be be initialized on the phpmailer object. As a result the mail does not get sent. wp_mail fails without an error, and the message shows.

**Comment by slaFFik** [comment]
Ok, make sense now. Thanks for the explanation! It's clear now. You may be correct in loading order issue.
We will check that.

**Comment by slaFFik** [comment]
@rlankhorst

I'm using the default in WordPress "Lost Password" link on `wp-login.php` and was able to successfully send and receive an email, while using `Other SMTP` mailer in WP Mail SMTP plugin.

Can you please share more details of what and how you do, which plugins may be is use and relates to this issue.

**Comment by privacyinsights** [comment]
Did you try this in a a multisite environment with the email variables set in the wpconfig.php? Theme my login is also enabled, but I had the same behaviour when resetting through the default reset. 

Currently we have solved the issue be reverting to the a previous version of the plugin.

**Comment by rlankhorst** [comment]
Did you try this in a a multisite environment with the email variables set in the wpconfig.php? Theme my login is also enabled, but I had the same behaviour when resetting through the default reset.

Currently we have solved the issue be reverting to the a previous version of the plugin.

**Comment by slaFFik** [comment]
I will recheck that, thanks for the update. I've updated the issue title to better reflect the real reason of the issue.

**Comment by slaFFik** [comment]
Closing this in favor of #100.
