### ISSUE TITLE
Management of capabilities

### ISSUE THREAD

**Issue by Inovagora** [awesomemotive/WP-Mail-SMTP#126]
Hello,

Thanks for this plugin!

We have a specific configuration concerning the management of our users capabilities. To have access to the settings of this plugin, it is necessary to have the capability "manage_options", but our users do not have this right.

Would you be able to add a hook to modify the right to access these settings?

Here is an example of what I'd like to see regarding this request.

Thank you very much.

## Screenshots
File src/Admin/Area.php, L282
![image](https://github.com/awesomemotive/WP-Mail-SMTP/assets/4538197/0b64a62f-b22f-4a6d-801f-84e238e834c3)

**Comment by alexander-sakal** [comment]
Hello @Inovagora 

Thank you for opening this issue!

We'll try to implement it in one of our future updates.

**Comment by Inovagora** [comment]
Hello @alexander-sakal,
Do you think you'll be able to implement this feature soon?

**Comment by alexander-sakal** [comment]
Hello @Inovagora. Yes, we are planning to include this in the next release.

**Comment by alexander-sakal** [comment]
Hello @Inovagora. We added a filter that allows to customize the capability required for managing the plugin.
Give it a shot and thank you for the suggestion!

Here is an example:

```
add_filter( 'wp_mail_smtp_core_get_capability_manage_options', function () {
	return 'manage_options';
} );
```
