### ISSUE TITLE
Tab support enhancement on setup wizard

### ISSUE THREAD

**Issue by heybran** [awesomemotive/WP-Mail-SMTP#127]
### Setup wizard step 2

Encryption radio should show a `focus` indicator (outline) to let users know it is being currently focused by `Tab` key.

### Setup wizard step 3

Similar to previous feedback, non-disabled email features checkbox should show styles difference when they're tabbed into by keyboard.

### Setup wizard step 4

`Yes, count me in` checkbox should have focus styles applied when tabbed into by keyboard.

### Setup wizard step 2

Users do not know when Encryption radio is tabbed into as it has no focus styles.

<img width="835" alt="Screenshot 2023-10-03 at 16 27 39" src="https://github.com/awesomemotive/WP-Mail-SMTP/assets/75633537/c656cf62-ebdb-4376-a7f4-dbd7bc99cbab">

### Setup wizard step 3

Non-disabled email features checkboxes has no focus styles.

<img width="835" alt="Screenshot 2023-10-03 at 16 34 39" src="https://github.com/awesomemotive/WP-Mail-SMTP/assets/75633537/e1dcde76-884d-48eb-af34-e5d300cfb9dd">

### Setup wizard step 4

`Yes, count me in` checkbox has no focus styles applied.

<img width="835" alt="Screenshot 2023-10-03 at 16 41 55" src="https://github.com/awesomemotive/WP-Mail-SMTP/assets/75633537/5806c402-db21-4ac4-8d94-7dadaab47399">

**Comment by heybran** [comment]
Tried to work on this issue, but got an error when running `composer build-lite`.

```
> wp-mail-smtp@3.9.0 gulp
> node ./node_modules/gulp/bin/gulp.js composer:create_vendor_prefixed_folder

[17:31:15] Using gulpfile ~/codes/docker/breeze-menu/wp-content/plugins/wp-mail-smtp/gulpfile.js
[17:31:15] Starting 'composer:create_vendor_prefixed_folder'...
[17:31:15] Finished 'composer:create_vendor_prefixed_folder' after 88 ms
Loading composer repositories with package information
                                                      
                                                                                             
  [RuntimeException]                                                                         
  The `url` supplied for the path (.packages/composer/phpcs-diff) repository does not exist  
```

Same error when I run `composer install`, if I may know what do I need to do to set up the dev environment?

My composer version is `1.10.27`, and my Node is `v20.3.1`.

### What I did was:

- Clone the repo
- Run `npm install`
- Run `composer install` or `composer build-lite` but encounter error reported above.

Do I need to install this package `.packages/composer/phpcs-diff` beforehand? If so, how do I find that package to install? Thanks a lot.

**Comment by alexander-sakal** [comment]
Hello @heybran 

Thank you for opening this issue and trying to resolve it!

Unfortunately, currently, development of the Setup Wizard in the public repository is not possible. We'll try to implement it in one of our future updates.

**Comment by heybran** [comment]
Hello @alexander-sakal 

Thank you for letting me know.

**Comment by alexander-sakal** [comment]
Hello @heybran. We enhanced tab support in the Setup Wizard in our latest release (v3.11.0).
Check it out and thanks for bringing it up!
