### ISSUE TITLE
Guzzle conflict

### ISSUE THREAD

**Issue by hughrun** [awesomemotive/WP-Mail-SMTP#136]
## Expected Behavior
Everything works fine.

## Current Behavior
I am getting an intermittent guzzle error: `Guzzle client error: Could not load a clean page to check` in the CiviCRM admin interface.

In my CiviCRM log I'm getting:
```
GuzzleHttp\Client returned cURL error 7: Failed to connect to example.com on port 443
```

This error is causing issues in my other plugin (CiviCRM). As far as I can tell it is caused by a conflict between their guzzle (7.6.1) and your Guzzle (7.8.1). I have attempted to upgrade for CiviCRM but it doesn't seem to work, and manually adjusting it every time one or other is upgraded is not sustainable.

## Possible Solution
As noted by your devs in #21 #48 and #81 namespacing your guzzle may resolve this conflict?

**Comment by hughrun** [comment]
hmm actually seems this probably isn't the cause after all.

**Comment by capuderg** [comment]
Hi @hughrun, we are "prefixing" with out own namespace any 3rd party library, so it should not cause any conflicts with other plugins.

Thank you for updating us, that our plugin was not the cause of your issues.
