### ISSUE TITLE
Causes HTML ERROR 500

### ISSUE THREAD

**Issue by hemiipatu** [awesomemotive/WP-Mail-SMTP#14]
## Plugin version 

1.3.2

## Current Behavior
After sometime, WP-Mail-SMTP seems to cause a website wide HTML ERROR 500. I came to the conclusion that it was indeed WP-Mail-SMTP causing this as renaming the folder for the plugin from the backend _(SSH)_ and refreshing the webpage of the site fixed it.

## Expected Behavior
Not to have a HTML ERROR 500

## Possible Solution
I am unsure on how this might be fixed as of yet, if you can provide details on what I can do to help: please let me know. ie. Provide logs

## Steps to Reproduce (for bugs)
It seems completely random when it occurs, there's no specific time when it might "trigger". But it is definitely the plugin.

**Comment by slaFFik** [comment]
@hemiipatu 
Could you please post here the error_log records right after seeing this white screen?
We are aware of one possible compatibility issue when some other plugin is using a really outdated version of Google libraries (we are using the latest version).

**Comment by slaFFik** [comment]
Should be fixed (I hope, as you didn't provide any details) in WP Mail SMTP 1.3.3, that will be released shortly.
Please reopen if the error is still there after the upgrade.
