### ISSUE TITLE
1.2.5 cannot be activated due to fatal error

### ISSUE THREAD

**Issue by MacLemon** [awesomemotive/wp-mail-smtp#147]
## Plugin version
1.2.5

## Current Behavior
Plugin crashes when trying to activate it.

## Expected Behavior
Plugin should not crash when activated.

## Steps to Reproduce (for bugs)

1. Download Plugin
2. Install Plugin
3. Activate Plugin
4. Crash

## Screenshots (if appropriate)

n/a

## Crash Report:
```
PHP Fatal error:  Uncaught Error: Call to undefined function WPMailSMTP\filter_var() in /usr/home/wordpressuser/example.com/wp-content/plugins/wp-mail-smtp/src/Options.php:464
Stack trace:
#0 /usr/home/wordpressuser/example.com/wp-content/plugins/wp-mail-smtp/src/Core.php(239): WPMailSMTP\Options->set(Array, true)
#1 /usr/home/wordpressuser/example.com/wp-includes/class-wp-hook.php(286): WPMailSMTP\Core->activate(NULL)
#2 /usr/home/wordpressuser/example.com/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#3 /usr/home/wordpressuser/example.com/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#4 /usr/home/wordpressuser/example.com/wp-admin/includes/plugin.php(586): do_action('activate_wp-mai...', NULL)
#5 phar:///usr/home/wordpressuser/wp-cli/wp-cli.phar/vendor/wp-cli/extension-command/src/Plugin_Command.php(284): activate_plugin('wp-mail-smtp/wp...', '', NULL)
#6 [internal function]: Plugin_Command->activate(Array, Array)
#7 phar:///u in /usr/home/wordpressuser/example.com/wp-content/plugins/wp-mail-smtp/src/Options.php on line 464
Fatal error: Uncaught Error: Call to undefined function WPMailSMTP\filter_var() in /usr/home/wordpressuser/example.com/wp-content/plugins/wp-mail-smtp/src/Options.php:464
Stack trace:
#0 /usr/home/wordpressuser/example.com/wp-content/plugins/wp-mail-smtp/src/Core.php(239): WPMailSMTP\Options->set(Array, true)
#1 /usr/home/wordpressuser/example.com/wp-includes/class-wp-hook.php(286): WPMailSMTP\Core->activate(NULL)
#2 /usr/home/wordpressuser/example.com/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#3 /usr/home/wordpressuser/example.com/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#4 /usr/home/wordpressuser/example.com/wp-admin/includes/plugin.php(586): do_action('activate_wp-mai...', NULL)
#5 phar:///usr/home/wordpressuser/wp-cli/wp-cli.phar/vendor/wp-cli/extension-command/src/Plugin_Command.php(284): activate_plugin('wp-mail-smtp/wp...', '', NULL)
#6 [internal function]: Plugin_Command->activate(Array, Array)
#7 phar:///u in /usr/home/wordpressuser/example.com/wp-content/plugins/wp-mail-smtp/src/Options.php on line 464
```

## Server System
OS: FreeBSD 11.1-p6
PHP: 7.1.14, php-fpm
Webserver: nginx 1.13.8
Wordpress: 4.9.3
l10n: german, english
MySQL: 5.7.20

## PHP modules:
```
php71-curl
php71-gd
php71-hash
php71-json
php71-mbstring
php71-mcrypt
php71-mysqli
php71-opcache
php71-phar
php71-zlib
```

**Comment by slaFFik** [comment]
`filter_var()` is a default PHP function. See here: http://php.net/manual/en/function.filter-var.php
If it doesn't exist, there is a problem with your PHP build. You need PECEL Filter extension.

**Comment by MacLemon** [comment]
Thanks for pointing me to the documentation of the filter *module*. After installing the additional module (and restarting the fpm process) the crash went away. No need to rebuild, let alone “check more options” for `make`.

Here's how to easily check if the module is present:
```
php -m | grep filter
```

May I suggest to add the list of required modules to the [Documentation](https://wordpress.org/plugins/wp-mail-smtp/)? It is missing from there.
This may also save you from more annoying bug reports like mine in the future.

**Comment by slaFFik** [comment]
@MacLemon Your report was the first one like that. We usually add something to documentation/description after several occurrences of the issue. But I will note that for myself and will monitor similar cases.

Thanks!
