### ISSUE TITLE
after verification 404 error 

### ISSUE THREAD

**Issue by setxnow** [awesomemotive/WP-Mail-SMTP#15]
after verification 404 error  

 Version 1.3.2 
 Randomly lost authentication on 2 sites ... one i got back this one wont redirect to success page instead giving a 404 error and failing to authenticate

**Comment by slaFFik** [comment]
This error most commonly occurs when the server is blocking requests needed to run SMTP when using Gmail mailer. 
To fix, you’ll need to contact your site’s hosting provider and ask them to disable specific rules within `mod_security` apache module, which they would determine using server logs.

**Comment by setxnow** [comment]
i am the host lol so what do i need to change?

**Comment by slaFFik** [comment]
I actually wrote what to do :)
1) check server logs about mod_security activity
2) find there a rule that was applied and blocked access to a site with `&scope=https://` in its url
3) modify/disable this rule to finish the auth process. 

This auth request is needed to be done only once, so the mod_security rule can be enabled after that.

**Comment by setxnow** [comment]
ok thanks .. i get to learn how to read server logs now lol been putting it off anyways

**Comment by toomanyairmiles** [comment]
> This error most commonly occurs when the server is blocking requests needed to run SMTP when using Gmail mailer.
> To fix, you’ll need to contact your site’s hosting provider and ask them to disable specific rules within `mod_security` apache module, which they would determine using server logs.

Like the other user I am the host, and have your plugin running on 40 sites. One site however produces a 404.

**Comment by capuderg** [comment]
Hi @toomanyairmiles,

you are running 40 sites, all on the same server and all are using our plugin with the Gmail mailer?

Does this site maybe have some additional security/firewall plugins, that might be causing this issue?

Do you have mod_security enabled on the server?

**Comment by toomanyairmiles** [comment]
No, all sites run the exact same config, all are on the same server with the same config.

mod_security is enabled, but there are no site spesific settings.

**Comment by capuderg** [comment]
Hi @toomanyairmiles,

could you please try to disable mod_security and try again for this site? We just need to be sure, that mod_security is not causing it (even if it worked OK on your other sites).
