### ISSUE TITLE
Incorrect mailer menu when options set via wpcli

### ISSUE THREAD

**Issue by gd-jroberts** [awesomemotive/wp-mail-smtp#152]
When wpcli is used to configure the options for wp-mail-smtp to use SMTP, the admin UI remains on PHP mail.

## Plugin version 
1.2.5

## Current Behavior

When wpcli is used to configure the options for wp-mail-smtp to use SMTP, the admin UI remains on PHP mail. I have to manually select the SMTP radio button before I can see the options, and I have to first save those settings before they will persist across reloads and sessions.

## Expected Behavior

The admin UI should detect which mailer is configured in the database or via wp-config.php environment variables and load the correct mailer settings. 

## Steps to Reproduce (for bugs)

1. Install wp-mail-smtp and configure it to use PHP mail, and save.
2. Execute the following via wpcli
```
wp option set mailer smtp --skip-themes --allow-root
wp option set mail_set_return_path true --skip-themes --allow-root
wp option set smtp-host smtp.mail.com --skip-themes --allow-root
wp option set smtp-port 465 --skip-themes --allow-root
wp option set smtp-enc-tls true --skip-themes --allow-root
wp option set smtp-user xxxxx --skip-themes --allow-root
wp option set smtp-pass xxxxx --skip-themes --allow-root
```
3. Login to site and load the wp-mail-smtp settings page.

**Comment by gd-jroberts** [comment]
Our use case:

We have development sites that use mailtrap and production sites that use PHP mail. We use ansible to configure both environments via wpcli.

**Comment by gd-jroberts** [comment]
I must have the option names wrong. Can you document what the option names should be?

**Comment by slaFFik** [comment]
Hi @gd-jroberts 

You are setting old options, that are no longer used starting from 1.x of the plugin. That's why setting them via wpcli has no effect in a new admin UI.

The best place to check the new options structure is this: https://github.com/awesomemotive/wp-mail-smtp/blob/develop/src/Options.php#L18

**Comment by gd-jroberts** [comment]
Is it still possible to get at those values using `wp option update` now that they are serialized?

Seems that I'd now need to export them into a json object, sed the value I want to change, and then feed the modified json back into the option.

I manage over 400 websites for a digital agency. While I can do it that way, I much prefer having the ability to directly change an option with `wp option update <option-name>`.

**Comment by gd-jroberts** [comment]
I came up with this which seems to do what I need:

```
wp option get wp_mail_smtp --format=json | jq '.mail.mailer = "mail"' | wp option update wp_mail_smtp --format=json
```
