### ISSUE TITLE
"Invalid token" MailGun error message is really cryptic.

### ISSUE THREAD

**Issue by dnunes** [awesomemotive/wp-mail-smtp#161]
## Plugin version 
Current.

## Current Behavior
When you use a wrong MailGun API Key, the only information that comes out is "debug: forbidden". 

## Expected Behavior
I would expect a descriptive error message. Only showing "Forbidden" does not reveal any kind of real debug information, specially for someone that is new to the plugin and doesn't know the inner workings of it (many programmers would assume some kind of file permissions problem, for logging or something).

## Possible Solution
If the error message say that the problem is a HTTP Call return from MailGun, it would be pretty obvious what the problem is.
Ideally we would have some kind of identifier from the class, like "MailGun Response: Forbidden" (it could easily be done in https://github.com/awesomemotive/wp-mail-smtp/blob/develop/src/Providers/Mailgun/Mailer.php#L307), to indicate where the error occurred.

## Steps to Reproduce (for bugs)
Simply:
1) install the plugin;
2) configure it for using MailGun;
3) input any wrong Private API Key for MailGun;
4) try a test email.

**Comment by slaFFik** [comment]
That's the only information that is provided by a Mailgun API when you use incorrect API key. There is nothing I can do here.

The whole `Debug` section is always a response from another API, and as you already know which mailer are you using - I don't think anything more specific should be added here.

Although there is an initiative #75, that might (or not) help with SG/MG/Gmail debug messages.
