### ISSUE TITLE
SMTP connect() failed. after update

### ISSUE THREAD

**Issue by niklaspoulsen** [awesomemotive/wp-mail-smtp#163]
## Plugin version 
Version 1.2.5 
## Steps to Reproduce (for bugs)

I have testet both SSL, TSL and NONE, also with Autentchion - nothing work.
Before update it was working...

After update the plugin, we now get an SMTP error. See screenshots for the error

## Screenshots (if appropriate)

<img width="1421" alt="skaermbillede 2018-03-14 kl 08 36 56" src="https://user-images.githubusercontent.com/32129061/37389556-14ee54fa-2765-11e8-8e0d-933e60304cdd.png">
<img width="1420" alt="skaermbillede 2018-03-14 kl 08 42 06" src="https://user-images.githubusercontent.com/32129061/37389557-15087fc4-2765-11e8-8c46-d426201796c2.png">

**Comment by slaFFik** [comment]
@niklaspoulsen
Which version were you updating from?
Have you tried SSL with both AutoTLS `on` and `off`?

**Comment by slaFFik** [comment]
@niklaspoulsen
Which version were you updating from?
Have you tried SSL with both AutoTLS `on` and `off`?

**Comment by slaFFik** [comment]
It's more a support request, which should be handled [here](https://wordpress.org/support/plugin/wp-mail-smtp).
