### ISSUE TITLE
SMTP connect() failure for gmail and outlook

### ISSUE THREAD

**Issue by gunbotmarket** [awesomemotive/wp-mail-smtp#164]
## Plugin version 
recent version

## Current Behavior
SMTP connect() failure for gmail and outlook, with both ssl and tsl connections
I discovered the failure is due to failing to verify the certificate when making the connection

## Possible Solution
As of PHP 5.6 you will get a warning/error if the SSL certificate on the server is not properly configured.

Gmail and Outlook use self signed certs so when php checks against the local certificate authority bundle, the connection will fail

so in this case, the connection must be made bypassing the cert verification

Connection: opening to smtp.gmail.com:587, timeout=300, options=array ( ‘ssl’ => array ( ‘verify_peer’ => false, ‘verify_peer_name’ => false, ‘allow_self_signed’ => true, ),)

this allows the smtp connection to gmail

please add this option to your plugin, to disable SSL certificate verification, to avoid these errors

**Comment by slaFFik** [comment]
It's more a support request, which should be handled [here](https://wordpress.org/support/plugin/wp-mail-smtp).

**Comment by slaFFik** [comment]
@gunbotmarket 
As discussed lots of times on a forum (see message above), we won't add an option, that will weaken security of emails deliverability. You can use this hack instead: https://gist.github.com/slaFFik/c1d7d4249f47da7195fb973109952090
