### ISSUE TITLE
PHPMailer SMTPAutoTLS option not disabled when using constants

### ISSUE THREAD

**Issue by ryanboswell** [awesomemotive/WP-Mail-SMTP#17]
## Plugin version 
1.3.3

## Current Behavior
When using the supported constants to pre-define the plugin config, the PHPMailer `SMTPAutoTLS` option is not overridden from the default of `true`, regardless of what the `WPMS_SSL` constant value is. This means that when we're disabling SSL in the plugin via constants PHPMailer still tries to force TLS if it thinks it can use it.

However, when using the admin settings, the `SMTPAutoTLS` option is set to `false` when the SSL option is set to `none`. This works as expected, and emails are able to be sent because PHPMailer does not try to force TLS.

## Expected Behavior
Using either the `WPMS_SSL` constant or the corresponding admin setting, when the option is set to `none` or is empty, the PHPMailer `SMTPAutoTLS` option should be set to false.

## Possible Solution
Fixing it should be relatively simple, since this is already handled appropriately when pulling config from the options table. When setting the PHPMailer config using constants, the `WPMS_SSL` constant value should be checked and when it is empty, the PHPMailer `SMTPAutoTLS` option should be set to `false`.

## Steps to Reproduce (for bugs)
1. Find an SMTP server you can use that does not use SSL.
2. Configure that server config using the supported constants [listed in the plugin](https://github.com/awesomemotive/WP-Mail-SMTP/blob/master/wp_mail_smtp.php#L31-L43).
3. Ensure that the `WPMS_SSL` constant is set to an empty string, per the notes on the definition.
4. Attempt to send an email using the Email Test page and see that it gets rejected because of a TLS error.

**Comment by slaFFik** [comment]
You should be using `WPMS_SMTP_AUTOTLS` constant to turn on/off `SMTPAutoTLS`.
`WPMS_SSL` only changes the `Encryption`.

Here is the exact place in code: https://github.com/awesomemotive/WP-Mail-SMTP/blob/master/src/Options.php#L335
