### ISSUE TITLE
Issue while sending testing email

### ISSUE THREAD

**Issue by koushal20** [awesomemotive/wp-mail-smtp#172]
There was a problem while sending a test email. Related debugging output is shown below:

Versions:
WordPress: 4.9.5
WordPress MS: No
PHP: 5.6.31
WP Mail SMTP: 1.2.5

Params:
Mailer: smtp
Constants: No
ErrorInfo: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Host: smtp.gmail.com
Port: 587
SMTPSecure: tls
SMTPAutoTLS: bool(true)
SMTPAuth: bool(true)

Server:
OpenSSL: Yes
SMTP Debug

![screenshot from 2018-04-22 13-31-42](https://user-images.githubusercontent.com/29223522/39092755-55cc0f80-4632-11e8-8a45-040e351a097d.png)
![screenshot from 2018-04-22 13-31-46](https://user-images.githubusercontent.com/29223522/39092756-55fa65a6-4632-11e8-8dc8-0091bd7e2540.png)
![screenshot from 2018-04-22 13-33-02](https://user-images.githubusercontent.com/29223522/39092757-562578d6-4632-11e8-89ff-a2b35e113bf2.png)

**Comment by slaFFik** [comment]
This is a server or settings configuration error, thus nothing to do in a plugin itself. So I'm closing this issue.

**Comment by slaFFik** [comment]
@koushal20 
Use the link https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting to read about possible reasons and how to fix that.
