### ISSUE TITLE
wp mail smtp not working

### ISSUE THREAD

**Issue by ven007** [awesomemotive/wp-mail-smtp#174]
I’m trying to use this plguin from a week and i tried everything , contacting my hosting provider and changing various settings , but nothing seems to work

whatever settings i put i get this same debug message . Can anyone please help

Versions:
WordPress: 4.9.5
WordPress MS: No
PHP: 7.0.29
WP Mail SMTP: 1.2.5

Params:
Mailer: smtp
Constants: No
ErrorInfo:
Host: localhost
Port: 25
SMTPSecure: string(0) “”
SMTPAutoTLS: bool(true)
SMTPAuth: bool(false)

Server:
OpenSSL: Yes
SMTP Debug:
[empty]

**Comment by slaFFik** [comment]
Deactivate all other SMTP related plugins (or email delivery). They are conflicting with WP Mail SMTP.
After their deactivation our WP Mail SMTP will start receiving correct options.

**Comment by ven007** [comment]
i disabled all the plugins , now i'm getting this error 

Versions:
WordPress: 4.9.5
WordPress MS: No
PHP: 7.0.29
WP Mail SMTP: 1.2.5

Params:
Mailer: smtp
Constants: No
ErrorInfo: Invalid address: (punyEncode) SMTP_FROM
Host: mail.custominkandthread.com
Port: 465
SMTPSecure: ssl
SMTPAutoTLS: bool(false)
SMTPAuth: bool(true)

Server:
OpenSSL: Yes
SMTP Debug:
2018-04-29 17:48:58	Invalid address: (punyEncode) SMTP_FROM

**Comment by slaFFik** [comment]
> Invalid address: (punyEncode) SMTP_FROM

Your FROM email is not supported (or incorrect). Please read the `ErrorInfo` and `SMTP Debug` sections in those error messages, they are there for a reason.

**Comment by ven007** [comment]
I know , but my from email is correct and I also changed it different
others but I still get the same error no matter what email id I put
