### ISSUE TITLE
I followed all directions to install plug in twice. when i try to authorize plugin with google I get an error message that says missing client_id. I have put the client id in there. deleted the api and create a new one for the second time and still get same error message. 

### ISSUE THREAD

**Issue by roselandoil** [awesomemotive/wp-mail-smtp#175]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Screenshots (if appropriate)

![image](https://user-images.githubusercontent.com/38989675/39646418-010a68f2-4fa1-11e8-833c-2500847ff333.png)

**Comment by slaFFik** [comment]
It's either #82 or you have not saved a correct client ID.
