### ISSUE TITLE
Configuration made with defined constants are not working as expected

### ISSUE THREAD

**Issue by cycomarcooo** [awesomemotive/WP-Mail-SMTP#18]
## Plugin version 
1.3.3

## Current Behavior

In my local environment I configure the plugin through constants so that emails are catched by mailHog on port 1025
```
/** WP-MAIL-SMTP */
define('WPMS_ON', true);
define('WPMS_MAIL_FROM', 'dev@dev.app');
define('WPMS_MAIL_FROM_NAME', 'Dev env');
define('WPMS_MAILER', 'smtp'); 
define('WPMS_SET_RETURN_PATH', false); 
define('WPMS_SMTP_HOST', 'localhost');
define('WPMS_SMTP_PORT', 1025);
define('WPMS_SSL', ''); 
define('WPMS_SMTP_AUTH', false);
```

In the plugin configuration page I can see that WPMS_MAIL_FROM and WPMS_MAIL_FROM_NAME are taken into account but when I use the Test email feature ("Email Test" tab), email is sent through port 25 and go right into the real recipient inbox instead of going to mailHog net.

Same thing occurs when using the plugin "check-email". Email goes right into the recipient inbox.

Here is a dump of the phpmailer object:
I don't understand why the mailer item is set to "mail"

```
[25-Jul-2018 12:56:26 UTC] [Area.php process_post line 400] WPMailSMTP\MailCatcher Object
(
    [action_function] => \WPMailSMTP\Processor::send_callback
    [Version] => 5.2.22
    [Priority] => 
    [CharSet] => iso-8859-1
    [ContentType] => text/plain
    [Encoding] => 8bit
    [ErrorInfo] => 
    [From] => root@localhost
    [FromName] => Root User
    [Sender] => 
    [ReturnPath] => 
    [Subject] => 
    [Body] => 
    [AltBody] => 
    [Ical] => 
    [MIMEBody:protected] => 
    [MIMEHeader:protected] => 
    [mailHeader:protected] => 
    [WordWrap] => 0
    [Mailer] => mail
    [Sendmail] => /usr/sbin/sendmail
    [UseSendmailOptions] => 1
    [PluginDir] => 
    [ConfirmReadingTo] => 
    [Hostname] => 
    [MessageID] => 
    [MessageDate] => 
    [Host] => localhost
    [Port] => 25
    [Helo] => 
    [SMTPSecure] => 
    [SMTPAutoTLS] => 1
    [SMTPAuth] => 
    [SMTPOptions] => Array
        (
        )

    [Username] => 
    [Password] => 
    [AuthType] => 
    [Realm] => 
    [Workstation] => 
    [Timeout] => 300
    [SMTPDebug] => 3
    [Debugoutput] => echo
    [SMTPKeepAlive] => 
    [SingleTo] => 
    [SingleToArray] => Array
        (
        )

    [do_verp] => 
    [AllowEmpty] => 
    [LE] => 

    [DKIM_selector] => 
    [DKIM_identity] => 
    [DKIM_passphrase] => 
    [DKIM_domain] => 
    [DKIM_private] => 
    [DKIM_private_string] => 
    [XMailer] => 
    [smtp:protected] => 
    [to:protected] => Array
        (
        )

    [cc:protected] => Array
        (
        )

    [bcc:protected] => Array
        (
        )

    [ReplyTo:protected] => Array
        (
        )

    [all_recipients:protected] => Array
        (
        )

    [RecipientsQueue:protected] => Array
        (
        )

    [ReplyToQueue:protected] => Array
        (
        )

    [attachment:protected] => Array
        (
        )

    [CustomHeader:protected] => Array
        (
        )

    [lastMessageID:protected] => 
    [message_type:protected] => 
    [boundary:protected] => Array
        (
        )

    [language:protected] => Array
        (
        )

    [error_count:protected] => 0
    [sign_cert_file:protected] => 
    [sign_key_file:protected] => 
    [sign_extracerts_file:protected] => 
    [sign_key_pass:protected] => 
    [exceptions:protected] => 
    [uniqueid:protected] => 
)
```

## Expected Behavior

By setting configuration through constants, I expect that all settings are taken into account, especially Port and host configuration.
The test function shall use this "hard coded" configuration.

## Steps to Reproduce (for bugs)

1. Setup wp-email-smtp constants into wp-config.php (or .env file or whatever WP config file)
2. Check the plugin admin page if constant are taken into account 
3. Go to the "Test Email" tab of the plugin admin page and send a test email
4. Check the recipient inbox and logs

## Screenshots (if appropriate)

![screen shot 2018-07-25 at 15 19 52](https://user-images.githubusercontent.com/1563647/43203366-5045d2e0-901e-11e8-8c51-667e4daa60f8.png)

**Comment by slaFFik** [comment]
@cycomarcooo 
Please make sure that no other SMTP-related plugins installed and activated. They may break compatibility.
I suspect something is rewriting global `$phpmailer` object, and breaking the configuration.

**Comment by cycomarcooo** [comment]
Hi @slaFFik, I create a wp installation from scratch with no other plugin and the default theme and I'm facing the same result. Am I missing something big? Can I kindly ask you to try to reproduce the thing on your side?

**Comment by sergeliatko** [comment]
Hi guys,

I have similar issue on live website https://www.mauicondohomes.com

Plugin was previously configured via admin settings. The I followed the advice about the password being set via wp-config.php and removed the password value from admin settings (left password field empty and saved)

Test email fails:

```
Versions:
WordPress: 4.9.8
WordPress MS: No
PHP: 7.1.20
WP Mail SMTP: 1.3.3

Params:
Mailer: smtp
Constants: No
ErrorInfo: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Host: mail.mauicondohomes.com
Port: 465
SMTPSecure: ssl
SMTPAutoTLS: bool(true)
SMTPAuth: bool(true)

Server:
OpenSSL: Yes
SMTP Debug:
2018-08-23 09:53:55	Connection: opening to ssl://mail.mauicondohomes.com:465, timeout=300, options=array (
)
2018-08-23 09:53:55	Connection: opened
2018-08-23 09:53:55	SERVER -> CLIENT: 220-host.techspokes.com ESMTP Exim 4.91 #1 Thu, 23 Aug 2018 00:53:55 -0900 
220-We do not authorize the use of this system to transport unsolicited, 
220 and/or bulk e-mail.
2018-08-23 09:53:55	CLIENT -> SERVER: EHLO www.mauicondohomes.com
2018-08-23 09:53:55	SERVER -> CLIENT: 250-host.techspokes.com Hello www.mauicondohomes.com [69.16.226.12]
250-SIZE 52428800
250-8BITMIME
250-PIPELINING
250-AUTH PLAIN LOGIN
250 HELP
2018-08-23 09:53:55	CLIENT -> SERVER: AUTH LOGIN
2018-08-23 09:53:55	SERVER -> CLIENT: 334 VXNlcm5hbWU6
2018-08-23 09:53:55	CLIENT -> SERVER: bm9yZXBseUBtYXVpY29uZG9ob21lcy5jb20=
2018-08-23 09:53:55	SERVER -> CLIENT: 334 UGFzc3dvcmQ6
2018-08-23 09:53:55	CLIENT -> SERVER:
2018-08-23 09:53:57	SERVER -> CLIENT: 535 Incorrect authentication data
2018-08-23 09:53:57	SMTP ERROR: Password command failed: 535 Incorrect authentication data
2018-08-23 09:53:57	SMTP Error: Could not authenticate.
2018-08-23 09:53:57	CLIENT -> SERVER: QUIT
2018-08-23 09:53:57	SERVER -> CLIENT: 221 host.techspokes.com closing connection
2018-08-23 09:53:57	Connection: closed
2018-08-23 09:53:57	SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
```

Works fine if I put the password back into the admin settings.

**Comment by sergeliatko** [comment]
the code in wp-config.php

```
/**
 * Configure mailing.
 */
define( 'WPMS_ON', true );
define( 'WPMS_SMTP_PASS', 'MyPassword' );
```

**Comment by codymorgan** [comment]
If it's helpful at all to the debugging, i'd like to mention that i am experiencing the same behavior, but with an additional variable:

I am using a wordpress multisite installation and the primary site seems to be reading the constants as expected, but subsites are only reading the from name, from email, and mailer field values, the rest are blank but uneditable.

**Comment by fagiani** [comment]
@slaFFik Any clues on this yet?

I'm also facing same issues of some of the ENVs not being set like `WPMS_SMTP_HOST` and `WPMS_SMTP_PORT` on a fresh install. 

It looks like some recent changes may have affected this behavior as it used to work fine. 

Some of the ENVs do reflect normally like `WPMS_MAIL_FROM`, `WPMS_MAIL_FROM_NAME` and `WPMS_MAILER` and below I've attached the error details if it helps.

![screen shot 2018-08-27 at 6 29 29 pm](https://user-images.githubusercontent.com/2450/44688699-6931ff00-aa2b-11e8-9aff-52c0a435fa65.png)

Keep Rocking!

**Comment by slaFFik** [comment]
@fagiani 
Check this: https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#could-not-instantiate-mail-function

@codymorgan WPMS has known issues, no ETA on a release with full WPMS support.

@sergeliatko 
You were connecting to `mail.mauicondohomes.com` but connected to `host.techspokes.com` instead. That's MITM attack or specific server configuration. Ask your hosting support to investigate, they seem to be rerouting SMTP requests to own servers. Also, make sure that the password in wp-config is properly displayed.

**Comment by slaFFik** [comment]
@cycomarcooo 
Something is definitely changing PHPMailer object settings on the fly. Try to clear all caches after saving settings in WP Mail SMTP.
That's not the issue with the plugin itself in this particular situation, so I'm closing the issue.

**Comment by sergeliatko** [comment]
@slaFFik 

> @sergeliatko
You were connecting to mail.mauicondohomes.com but connected to host.techspokes.com instead. That's MITM attack or specific server configuration. Ask your hosting support to investigate, they seem to be rerouting SMTP requests to own servers. Also, make sure that the password in wp-config is properly displayed.

Thanks, that's the same physical server actually... host.techspokes.com is the name of the server where mail.mauicondohomes.com is located. Not sure what to ask the host about exactly. Do I just give them the debug file to check?

**Comment by slaFFik** [comment]
@sergeliatko 
Yes, give them that **SMTP Debug:** log and ask why do you get this error and that you are sure that auth data is correct. And also why you are connected to `host.techspokes.com` when SMTP requests is initiated to `mail.mauicondohomes.com`.

**Comment by sergeliatko** [comment]
@slaFFik Thanks mate, helped me out. Спасибо, выручил.

**Comment by drzraf** [comment]
I think I got the problem (please reopen):

Minimal `config.php` file:
```php
define("WPMS_ON", true);
define("WPMS_SMTP_HOST", "bar");
```

`wp eval 'echo((new WPMailSMTP\Options())->get("smtp","host"));'`
// output "bar"

Now lets set an simple option in database (what happen easily by mistake/misunderstanding):
`wp option set --format=json wp_mail_smtp '{"smtp":{"autotls":true}}'`

Then:
`wp eval 'echo((new WPMailSMTP\Options())->get("smtp","host"));'`
// output nothing

I strongly believe most people above have stale values inside `wp_mail_smtp`.

Issue lays in https://github.com/awesomemotive/WP-Mail-SMTP/blob/master/src/Options.php#L209
```php
		if ( isset( $this->_options[ $group ] ) ) {
			// Get the options key of a group.
			if ( isset( $this->_options[ $group ][ $key ] ) ) {
				$value = $this->get_const_value( $group, $key, $this->_options[ $group ][ $key ] );
			} else {
				$value = $this->postprocess_key_defaults( $group, $key );
			}
		} else {
			// check on maps
			if ( isset( self::$map[ $group ] ) && in_array( $key, self::$map[ $group ] ) ) {
				$value = $this->get_const_value( $group, $key, false );
			} else {
				$value = $this->postprocess_key_defaults( $group, $key );
			}
		}
```

`get_const_value()` grabs values from `wp-config.php`.
But it will only apply if, not only the key, but the **group** the option belong to does not exist in database. Having any option belonging to `smtp` (eg: `autotls`) keeps any other key set in `wp-config.php` from being taken into account.
This may only apply to the `new codebase` (people with PHP >=  5.3.6)

IMHO, this clearly calls for a fix. Database must not override PHP constants.

**Comment by slaFFik** [comment]
@drzraf 
Hi, thanks for sharing! 
I will check all that this or the following week.

**Comment by slaFFik** [comment]
@drzraf
I can finally confirm the issue. Thank you very much! This will definitely be fixed in WP Mail SMTP 1.4.0.

Although your `wp` commands generated a ton of errors for me, I was able to replicate the behavior using the idea behind your commands.

<details>
<summary>Errors</summary>

```
PHP Warning: Use of undefined constant smtp - assumed 'smtp' (this will throw an Error in a future version of PHP) in phar://C:/OpenServer/modules/php/PHP-7.2-x64/wp-cli.phar/vendor/wp-cli/eval-command/src/Eval_Command.php(37) : eval()'d code on line 1
PHP Warning: Use of undefined constant host - assumed 'host' (this will throw an Error in a future version of PHP) in phar://C:/OpenServer/modules/php/PHP-7.2-x64/wp-cli.phar/vendor/wp-cli/eval-command/src/Eval_Command.php(37) : eval()'d code on line 1
```
</details>


---

I'm closing this issue, as I'm working on a fix in another repository (this repo is just a release mirror and to track publicly created issues).

**Comment by drzraf** [comment]
The wp-cli warning you mention seems related to a quoting issue. Maybe related to you windows command line syntax/handling.

**Comment by F4FXL** [comment]
Hi,

I had a smilar issue, after moving password to wp-config.php test email failed. The issue was caused by cached php files. I had to clear OPCache and then it worked.
