### ISSUE TITLE
Will not let me send by any method

### ISSUE THREAD

**Issue by tuenweb** [awesomemotive/wp-mail-smtp#181]
Good morning, after configuring everything I receive this error, any ideas? :(

Versions:
WordPress: 4.9.6
WordPress MS: No
PHP: 7.0.30
WP Mail SMTP: 1.2.5

Params:
Mailer: gmail
Constants: No
Client ID/Secret: Yes
Auth Code: Yes
Access Token: Yes

Server:
OpenSSL: Yes
PHP.allow_url_fopen: Yes
PHP.stream_socket_client(): Yes
PHP.fsockopen(): Yes
PHP.curl_version(): Yes
Apache.mod_security: No

**Comment by slaFFik** [comment]
Hi @tuenweb 
This is a development repository, not a support forum. Please read the [forum history](https://wordpress.org/support/plugin/wp-mail-smtp), most likely similar questions were already answered, multiple times.
As you cut out part of the Debug output, I can't help you. You seem to have access token saved, try to clean the site object cache if you have it.
