### ISSUE TITLE
Compatibility with PHP 7.2?

### ISSUE THREAD

**Issue by UpstateGuy** [awesomemotive/WP-Mail-SMTP#19]
Needing to update PHP on WordEngine -- ran compatibility checker and received the results below -- 4 warnings and 5 errors.  Will this be resolved if/when I move to PHP 7.2?

## Plugin version 1.3.3.

FILE: /nas/content/live/onondagabar/wp-content/plugins/wp-mail-smtp/vendor/guzzlehttp/promises/src/functions.php
----------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 3 WARNINGS AFFECTING 3 LINES
----------------------------------------------------------------------------------------------------------------
 222 | WARNING | Function each() is deprecated since PHP 7.2; Use a foreach loop instead
 257 | WARNING | Function each() is deprecated since PHP 7.2; Use a foreach loop instead
 313 | WARNING | Function each() is deprecated since PHP 7.2; Use a foreach loop instead
----------------------------------------------------------------------------------------------------------------

FILE: /nas/content/live/onondagabar/wp-content/plugins/wp-mail-smtp/vendor/phpseclib/phpseclib/phpseclib/bootstrap.php
----------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------------
 10 | WARNING | INI directive 'mbstring.func_overload' is deprecated since PHP 7.2
----------------------------------------------------------------------------------------------------------------------

FILE: /nas/content/live/onondagabar/wp-content/plugins/wp-mail-smtp/vendor/phpseclib/phpseclib/phpseclib/Crypt/Random.php
-------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 5 ERRORS AFFECTING 2 LINES
-------------------------------------------------------------------------------------------------------------------------------------------------------
  69 | ERROR | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
  69 | ERROR | Function mcrypt_create_iv() is deprecated since PHP 7.1 and removed since PHP 7.2; Use random_bytes() or OpenSSL instead
 108 | ERROR | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 108 | ERROR | Function mcrypt_create_iv() is deprecated since PHP 7.1 and removed since PHP 7.2; Use random_bytes() or OpenSSL instead
 108 | ERROR | The constant "MCRYPT_DEV_URANDOM" is deprecated since PHP 7.1 and removed since PHP 7.2
-------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by slaFFik** [comment]
Plugin is fully compatible with PHP 7.2.
These errors are in a lib that is using certain techniques as fallbacks for older PHP versions.
