### ISSUE TITLE
Notice when using WP-CLI

### ISSUE THREAD

**Issue by noplanman** [awesomemotive/wp-mail-smtp#2]
When using WP-CLI, the following notice gets printed:
```
PHP Notice:  Undefined index: SERVER_NAME in /vagrant/content/plugins/wp-mail-smtp/wp_mail_smtp.php on line 458
```

This is due to the fact that CLI has no `SERVER_NAME`.
Instead, it could just be `local-cli` or something like that.

I can PR if you wish.

*Off-topic:*
How can this plugin only have my star on GitHub with 500'000+ active installs?!

**Comment by slaFFik** [comment]
One of the possible solutions: https://stackoverflow.com/questions/626416/php-server-name-from-command-line

**Comment by noplanman** [comment]
@slaFFik That could be an option as well. Anything really, just to make sure the variable is set and the error doesn't pop up 😊

**Comment by slaFFik** [comment]
@noplanman 
I can't replicate the issue.

Can you share the CLI command that generated that notice?

**Comment by slaFFik** [comment]
Oh, disregard the previous message.
