### ISSUE TITLE
Conflics between guzzle latest version and guzzle used in this plugin

### ISSUE THREAD

**Issue by atquest** [awesomemotive/WP-Mail-SMTP#21]
The guzzle version included in the latest version of WP-Mail-SMTP conflicts with the latest version of guzzle (as included in other plugins)

**Comment by slaFFik** [comment]
@atquest

How is that visible on a site? What are the errors?
Which other plugins are you talking about?

I assume you are on WP Mail SMTP 1.3.3 and Gmail mailer (you haven't explicitly defined that). That issue template is there for a reason, please follow its structure.

**Comment by slaFFik** [comment]
We are using `"google/apiclient": "2.2.2"` library, that has own dependencies that are updated for each release. So for WP Mail SMTP 1.3.0 they were the latest.
WP Mail SMTP 1.4.0 is still using `"google/apiclient": "2.2.2"` - as no newer version released, but its dependecies are updated (like `google/apiclient-services (v0.64 => v0.74)`), and I can't control that. 

Here is the list of updated packages: 
![image](https://user-images.githubusercontent.com/282234/48952417-c7974c80-ef4a-11e8-9d57-2e42c2e8e201.png)
As you can see, no update for guzzle, that means either no new version of it, or Google'e libraries that we are using are stuck with a specific guzzle version, that I can't change not to break Google API integration.

Here is the guzzle version that is required by `google/apiclient"`: `"guzzlehttp/guzzle": "~5.3.1|~6.0"`
This is the installed version: 6.3.3 - 2018-04-22.
And it's actually the latest guzzle version: https://github.com/guzzle/guzzle/releases

So the bottom line - that's the issue with other plugins not using the latest guzzle version.
