### ISSUE TITLE
Mailgun EU Support

### ISSUE THREAD

**Issue by Jensderond** [awesomemotive/WP-Mail-SMTP#22]
Cannot use this plugin with mailgun when region of mailgun is set to EU.

## Plugin version 
1.3.3

## Current Behavior
Debug:
Mailer: Mailgun
Domain not found: domain.com

## Expected Behavior
Expected the domain to be found on mailgun's eu servers.

## Possible Solution
Also check eu.mailgun.com for the domain.

**Comment by slaFFik** [comment]
@Jensderond 
It's a known issue. Will be fixed in the upcoming v1.4.0.
