### ISSUE TITLE
v1.3.3, v1.4.0 - requests full gmail permissions

### ISSUE THREAD

**Issue by jacobschloss** [awesomemotive/WP-Mail-SMTP#23]
## Plugin version 
Version 1.3.3

## Current Behavior
Plugin requests full access to gmail, including reading email, deleting email, etc on the OATH page

## Expected Behavior
Only send access (https://www.googleapis.com/auth/gmail.send) to be requested via OATH

## Steps to Reproduce (for bugs)

1. Set up google api project, key
2. Configure plugin using key and secret
3. On Oauth page, it will ask for full permissions 

## Screenshots (if appropriate)

![image](https://user-images.githubusercontent.com/2883354/48667903-e81c5e00-ea95-11e8-9f2e-854c7185f337.png)

**Comment by jacobschloss** [comment]
Same behavior in 1.4.0. [https://wpforms.com/how-to-securely-send-wordpress-emails-using-gmail-smtp/#comment-118167](url) implies that this was needed to fix operation on some sites, but this is a non-starter for some users - we can't allow the possibility that this plugin can read or delete mail from the attached gsuite account.

Is there another workaround for the affected sites?

**Comment by slaFFik** [comment]
I understand the frustration, but we need this for future.
We use full gmail access to get the associated email address, and in the future to get access to settings - "Send As", that will allow defining different senders for emails. Currently, Gmail API doesn't allow to modify that (all emails are sent from your connected account), and we plan to fix that.
As the plugin is opensource - you can check all the usage.
