### ISSUE TITLE
v1.4.0 - using 0 for SMTP Port results in "Mail is not properly configured" error

### ISSUE THREAD

**Issue by 84webdev** [awesomemotive/WP-Mail-SMTP#24]
For using the plugin with GoDaddy's mail server (relay-hosting.secureserver.net), the SMTP port needs to be set to 0. This works fine for versions 1.3.3 and below.

However, after updating to version 1.4.0 today, the Email Test page throws a "Mail is not properly configured error" when the SMTP port is set to 0. At that point, it's not possible to send a test email and I'm assuming that other email isn't working either.

Setting the port to 80 and the error goes away, however the email test fails due to the port being wrong.

Deleting version 1.4.0 plugin files and putting 1.3.3 back, and it's working fine with port 0 again.

Thanks!

**Comment by slaFFik** [comment]
Have you tried port 25? I see people using port 25 with that host everywhere.

https://www.godaddy.com/community/Managing-Email/Can-t-Get-GoDaddy-Hosting-and-PHPMailer-to-work/td-p/57698
https://o365info.com/configure-your-wordpress-site-to-send-e-mail-via-godaddy-mail-server-shared-hosting-plan-part-6-6/
https://www.prestashop.com/forums/topic/143911-solvedhow-to-use-godaddys-smtp-email-settings/
Additional information: https://www.mailgun.com/blog/which-smtp-port-understanding-ports-25-465-587

You can't use port 0, the OS will understand as "use any positive number port number" and may select it randomly. So technically speaking port 0 is an incorrect value - that why we require a positive value there.

**Comment by 84webdev** [comment]
Understood - I just tested with port 25 as you suggested and it's working fine with version 1.4.0.

Thanks very much for your help and keep up the great work!
