### ISSUE TITLE
Grammar issues in Google mailer notices

### ISSUE THREAD

**Issue by jessquig** [awesomemotive/WP-Mail-SMTP#25]
## Current Behavior

1. There's the same grammar issue in 2 (or technically 4) places: "Gmail doesn't allow to override From Email." and "Gmail doesn't allow to override From Name." (the "doesn't allow to override" part).

2. There's duplicate text for the From Email and then twice for the From Name (http://cloud.supportally.com/559bd5481345)

## Possible Solution

1. Better phrasing would be "Gmail doesn't allow From ___ to be overridden". 

2. Remove one line of info text in each section so it's only stated once.

**Comment by slaFFik** [comment]
Issue moved to [awesomemotive/wp-mail-smtp-plugin #227](https://github.com/awesomemotive/wp-mail-smtp-plugin/issues/227) via [**ZenHub**](https://www.zenhub.com/)
