### ISSUE TITLE
Test page doesn't work when using defined constants and Other SMTP mailer

### ISSUE THREAD

**Issue by jacobischwartz** [awesomemotive/WP-Mail-SMTP#27]
When I view this plugin's setting page, I see all the right settings (greyed out). But when I click over to this plugin's test page, the plugin reports that I don't have the sending method configured and that it can't send a test.

I've got a multisite install, am using this plugin version 1.4.1 network-activated and have defined all config items in wp-config.php. I'm using the Other SMTP mailer. 

## Plugin version 
1.4.1

## Current Behavior
The test page reports "You cannot send an email. Mailer is not properly configured. Please check your settings." and the Send Email button is greyed out.

## Expected Behavior
No error displayed, and I should be able to send the test email.

## Possible Solution
There is a bug preventing defined constants from being read in this situation. The bug is in one of these locations:
WPMailSMTP\Providers\SMTP\Mailer::is_mailer_complete()
or
WPMailSMTP\Options::get_group()

I was able to resolve the issue by changing is_mailer_complete() to use get(), which does inspect defined constants, instead of get_group(), which does not. I don't see any other usages of get_group() for the Other SMTP mailer, so this was the only change that was needed for my use case.

Here is the complete method code per my modifications:
`

	public function is_mailer_complete() {

		// Host and Port are the only really required options.
		if (
			! empty( $this->options->get($this->mailer, 'host') ) &&
			! empty( $this->options->get($this->mailer, 'port') )
		) {
			return true;
		}

		return false;
	}

`

## Steps to Reproduce (for bugs)
Here are the defined constants in my wp-config.php (with specific account details replaced as XXX). They are the same as commented in wp_mail_smtp.php:

define( 'WPMS_ON', true ); // True turns on the whole constants support and usage, false turns it off.
define( 'WPMS_MAIL_FROM', 'XXX' );
define( 'WPMS_MAIL_FROM_FORCE', true ); // True turns it on, false turns it off.
define( 'WPMS_MAIL_FROM_NAME', 'XXX' );
define( 'WPMS_MAIL_FROM_NAME_FORCE', true ); // True turns it on, false turns it off.
define( 'WPMS_MAILER', 'smtp' ); // Possible values: 'mail', 'gmail', 'mailgun', 'sendgrid', 'smtp'.
define( 'WPMS_SET_RETURN_PATH', true ); // Sets $phpmailer->Sender if true.
define( 'WPMS_SMTP_HOST', 'smtp.mandrillapp.com' ); // The SMTP mail host.
define( 'WPMS_SMTP_PORT', 587 ); // The SMTP server port number.
define( 'WPMS_SSL', 'tls' ); // Possible values '', 'ssl', 'tls' - note TLS is not STARTTLS.
define( 'WPMS_SMTP_AUTH', true ); // True turns it on, false turns it off.
define( 'WPMS_SMTP_USER', 'XXX' ); // SMTP authentication username, only used if WPMS_SMTP_AUTH is true.
define( 'WPMS_SMTP_PASS', 'XXX' ); // SMTP authentication password, only used if WPMS_SMTP_AUTH is true.
define( 'WPMS_SMTP_AUTOTLS', true ); // True turns it on, false turns it off.

**Comment by ekandreas** [comment]
Vote up for fixing this issue. Annoying nag in WP as a result. You should filter the nag so it can be removed in specific situations.

**Comment by lkraav** [comment]
This is real. Seeing the same bug right now on my multisite.

**Comment by slaFFik** [comment]
Thanks for the report.

This will be fixed in the next plugin release.

**Comment by spenserhale** [comment]
@slaFFik I wrote a PR that fixes the Options::get_group() method instead of fixing this one mailer: #35. If you could please review. I had a question since Options::get_group() and Options::get_all() used different styles; which one should plugin go forward with.

**Comment by slaFFik** [comment]
As `Options::get_group()` will be improved, I'm closing this PR.

**Comment by slaFFik** [comment]
Seems to be fixed in #35.
