### ISSUE TITLE
WPMS_SMTP_AUTHTLS is being ignored if set to false

### ISSUE THREAD

**Issue by fabianonline** [awesomemotive/WP-Mail-SMTP#29]
Since I have to connect to my SMTP server locally, I can't use encryption. So I have to set AutoTLS to false to prevent it from using STARTTLS and creating certificate mismatches.

I put `define('WPMS_SMTP_AUTHTLS', false);` into wp-config.php, but it is being ignored.

The bug seems to be in `is_const_defined`:

https://github.com/awesomemotive/WP-Mail-SMTP/blob/f8aca0b8310f027985b96e7e0fc82e784202d64f/src/Options.php#L477

`defined( 'WPMS_SMTP_AUTOTLS' )` returns `true`, but `WPMS_SMTP_AUTOTLS` is `false`, so the code returns `false` meaning "the constant is not defined" leading to the later code ignoring the constant. Commenting out the `&& WPMS_SMTP_AUTOTLS` part fixes that bug for me.

**Comment by slaFFik** [comment]
Oh, good catch!
Will be fixed in the next plugin release.

Thank you!

**Comment by timotheemoulin** [comment]
Hi, this bug is still present in the latest 1.9.0 release. 06.04.2020

**Comment by capuderg** [comment]
Hi,

in the title and the original message of this issue the constant mentioned is `WPMS_SMTP_AUTHTLS`, but that is not the correct name of the constant in question. The correct one is `WPMS_SMTP_AUTOTLS`.

Is that causing the issue?

**Comment by timotheemoulin** [comment]
Hello,
The issue comes from that a falsy value (0, false, null, '') is considered
to be undefined by the method that checks if the constant has been defined.

Cheers,
tim

>

**Comment by capuderg** [comment]
The line in question was updated: https://github.com/awesomemotive/WP-Mail-SMTP/blob/master/src/Options.php#L632

I also debugged it and when I added these two lines to the config.php file:

```
define( 'WPMS_ON', true );
define( 'WPMS_SMTP_AUTOTLS', false );
```

The `is_const_defined` returns `false` for the `autotls` option.

**Comment by timotheemoulin** [comment]
Yes @capuderg this is the line that makes me struggle. The function returns `true` only if the constant has been defined to `'true'` or `true`.

**Comment by capuderg** [comment]
Hmm... I'm sorry, but I don't understand (I'm a bit confused)... What kind of value (X) would you like to set in this line:

`define( 'WPMS_SMTP_AUTOTLS', X );`

And what are you expecting the outcome for `is_const_defined( 'smtp', 'autotls' )` method to be?

These constants/settings are supposed to be boolean, so `true` and `false` are expected to be set and the same values are expected from the `is_const_defined` method.

**Comment by timotheemoulin** [comment]
I would like to set 
`deine( 'WPMS_SMTP_AUTOTLS', false );`
but if I do so, `is_const_defined` returns that the constant is not defined, which is not true as I defined it to `false`.

In my opinion, the method should only check `$return = defined( 'WPMS_SMTP_AUTOTLS' )` and not if there is a truthy value inside.

**Comment by capuderg** [comment]
Ohh, I see now, I'm sorry, I didn't check how this method is used elsewhere in code... :(

I see the issue now. But I think additional fixes in code are needed as well. 

We'll fix this for the next release.

Thanks for your patience.
