### ISSUE TITLE
SSL issues due to bad certificate

### ISSUE THREAD

**Issue by slaFFik** [awesomemotive/wp-mail-smtp#29]
https://wordpress.org/support/topic/problems-with-php-version-5-6-or-later/

And in general: https://wordpress.org/search/ssl+intext%3A%22Plugin%3A+WP+Mail+SMTP+by+WPForms%22/?forums=1

I think, this can be fixed with a new setting, that will allow to omit this SSL check.

**Comment by jaredatch** [comment]
Perhaps this is something we can make a filter or hidden setting for?

**Comment by jaredatch** [comment]
I assume you're talking about `sslverify`? Did we put a filter in place in v1? If so let's close this. If not, we should consider it for the release of for a follow up update.

**Comment by slaFFik** [comment]
We have a `phpmailer` object filter to modify `SMTPOptions`, where `sslverify` should be placed.
Implementing a hack into a plugin for a misconfigured server is a bad practice. So closing this issue.
