### ISSUE TITLE
WP 3.6 compat: Fatal error in PhpMailer while sending test email

### ISSUE THREAD

**Issue by andriusr** [awesomemotive/WP-Mail-SMTP#30]
## Plugin version 
1.4.1
PHP version 5.4
WP version 3.9
## Current Behavior

When sending email, error message is generated (in the blank page):
Fatal error: Call to undefined method WPMailSMTP\MailCatcher::getCustomHeaders() in /home/public_html/wp-content/plugins/wp-mail-smtp/src/MailCatcher.php on line 53

Probably this is related to older WP version I am using. Compability with 3.6+ was stated, it seems it is not perfect.

## Expected Behavior

Test email should be send.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by slaFFik** [comment]
@andriusr 
I've tested email delivery with WordPress 3.6, so it should work.
But I will retest again.

Would be helpful, if you could provide more details about your plugin settings, nothing private, just general things:
1. localhost or live site, 
1. mailer used (just to be sure), 
1. are you using constants to set up the plugin or plugin admin area?
1. do you have other SMTP related plugins activated?
1. does real WordPress or forms plugins emails work for you? So basically is it just test email that fails or all emails are generating errors and/or not delivered.

**Comment by andriusr** [comment]
Hi Slava,I found what was an issue - class-phpmailer.php was outdated on my instance with come classes missing. I got recent version for github and started to work. 
Andrius

**Comment by slaFFik** [comment]
Thanks for an update.

Do you mean that you "patched" WordPress itself with an updated version of that library? We do not provide a newer version inside our plugin, for compatibility reasons.

**Comment by andriusr** [comment]
Yes, I replaced library in Wordpress instance.   public $Version = '5.2.22'; works with 3.9 without issues.

**Comment by HarveyDoom** [comment]
Can confirm this bug was present on one of my wordpress sites as well. 
This site is using Wordpress 4.2.2
Error was the same 'Call to undefined method WPMailSMTP\MailCatcher::getCustomHeaders()'.
Appeared even after all other plugins were disabled. 
Fixed by replacing class-phpmailer with 5.2.22 @andriusr Thanks mate!

**Comment by slaFFik** [comment]
Will be fixed in the next version of WP Mail SMTP.
