### ISSUE TITLE
WP.org icons & banners & screenshots

### ISSUE THREAD

**Issue by slaFFik** [awesomemotive/wp-mail-smtp#31]
Banners & icons of 2 sizes each + their RTL version + screenshots (even `.gif` if appropriate).

https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/

- [x] Icon 1x
- [x] Icon 2x
- [x] Banner 1x
- [x] Banner 2x
- [ ] ~Banner 1x RTL~
- [ ] ~Banner 2x RTL~
- [x] Updated screenshots

**Comment by slaFFik** [comment]
@jaredatch Will we update them for 0.11?

**Comment by jaredatch** [comment]
I'll get the icon updated today hopefully. The banner we will definitely add, but need to get with Dalton to come up with something and then have it approved.

**Comment by jaredatch** [comment]
I don't believe RTL banners are relevant anymore since with new plugin directory no longer overlays text on top of the banners.
