### ISSUE TITLE
Email delivery error WP mail SMTP

### ISSUE THREAD

**Issue by MarielOlivasEduTrav** [awesomemotive/WP-Mail-SMTP#31]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by slaFFik** [comment]
Hi @MarielOlivasEduTrav 

You haven't filled the details about your issue.
Could you please follow the template and fill all the sections with information related to your problem?

**Comment by jaredatch** [comment]
Due to no follow up, closing.
