### ISSUE TITLE
Double byte characters in from/to/message fields cause email to fail silently

### ISSUE THREAD

**Issue by markchitty** [awesomemotive/WP-Mail-SMTP#32]
### Plugin version and configuration
* v1.3.3
* Mailer = Other SMTP
* SMTP settings = localhost:1025, no encryption

### Current Behavior
1. 
    * Create an email in Wordpress (e.g. via a contact form or similar)
    * Submit the form to trigger the email being sent.
    * Email is sent \o/
2.
    * Create an email in Wordpress (e.g. via a contact form or similar)
    * **Include double-byte characters in the message (or from/to fields)**
    * Submit the form to trigger the email being sent.
    * wp_mail() returns true, but no email is sent. :-(

### Expected Behavior
Email should be sent.

### Possible Solution
Took me a fair bit of diagnosing to narrow this down (as a typical developer I assumed the problem was in my own code rather than a library), but the problem goes away if I set Mailer to Default (none). Fine for dev site but not a great solution in production.

**Comment by lkraav** [comment]
I also discovered silent fail SMTP issues y-day, and switched to Post SMTP. But would be interesting to know what's wrong here, too.

@markchitty bite -> byte? :)

**Comment by markchitty** [comment]
@lkraav Oops! Good spot ✔️. Fixed. (Got it right in the body text tho :)

**Comment by slaFFik** [comment]
That's interesting.

@markchitty Are you talking about DBC in `From Name`, `From Email` and `To` (recipient).
I would be thankful for a working example of text to check.

**Comment by markchitty** [comment]
Yes, any DBC in the `From`, `To` headers, or in the message body.

Characters such as bullet, emojis, etc trigger the issue. So a `•` will cause the email to fail whereas `&#x95;` or `&bull;` (html entity code for the same character) are fine.

Fancy quotes (not the usual single quote character) tend to be the problem in the from/to fields - happens if people cut-n-paste a name like _O'Toole_ from a word processing app.

**Comment by slaFFik** [comment]
Awesome, thank you!
I will investigate that in details.

**Comment by slaFFik** [comment]
Unfortunately, I wasn't able to replicate. I've tried that dot from above, and also something like `熊本大学` in headers (`From`) and message content - everything works fine.
So I'm closing this issue.
