### ISSUE TITLE
Links in emails are being replaced, 'unsubscribe' is added

### ISSUE THREAD

**Issue by DobreBiuro** [awesomemotive/WP-Mail-SMTP#34]
I found that all links in emails sent after I installed WP SMTP v1.4.1 are replaced strangely.
Additionally to every email sent is also added 'unsubscribe' link (also invalid).
In these 2 screens you can see the links in status bar:

https://www.dropbox.com/s/ntzva01g6xeibgw/Zrzut%20ekranu%202019-01-12%2020.54.25.png?dl=0

https://www.dropbox.com/s/5htddfp0uihr006/Zrzut%20ekranu%202019-01-12%2020.54.51.png?dl=0

Yes, even test email links are broken!

## Plugin version 
1.4.1

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by lkraav** [comment]
Specify which gateway you're using. Many have what you describe as standard functionality, and those elements are added after WP Mail SMTP has sent the e-mail to gateway.

**Comment by DobreBiuro** [comment]
The gateway was 'other smtp.' I configured it to my mailgun settings. I had to use 'other smtp' option because standard mailgun option didn't work at all.

**Comment by lkraav** [comment]
Either way, it's Mailgun adding those elements.

**Comment by jaredatch** [comment]
Normally I'd say it's another plugin, but since you said the plugin didn't appear until after you setup SMTP, that's obviously not the case

I would try using a different SMTP Host or different mailer.

My best guess is the SMTP host is filtering the message and adding "unsubscribe" at the bottom to combat spam and improve deliverability.

That text isn't coming from WP Mail SMTP however, that string does't even exist 😮

https://cl.ly/bdcaf227aaec

**Comment by DobreBiuro** [comment]
Oke, it can be idd issue at mailgun. I'll contact them tomorrow and whenever they will confirm, I will close this issue. Thanks for your support!

**Comment by jaredatch** [comment]
@amblyline yeah please follow up and let us know!

If that is something Mailgun is adding, then we need to see are we able to disable that feature or is it something new that you can't turn off. 

I don't recall them doing anything like this previously, but wouldn't surprise me they added (and forced) something like this to keep their deliverability good.

**Comment by jaredatch** [comment]
@amblyline I did some testing in MG and think I found it.

https://cl.ly/8944f46e1154

If those settings are not off (which they probably are not by default), you end up with what you described. So if you're using MG, check those settings.

**Comment by slaFFik** [comment]
Closing this issue, as this is a Mailgun service configuration (which we don't control), not the plugin itself or its compatibility with Mailgun API.

**Comment by DobreBiuro** [comment]
@jaredatch indeed there was a configuration you showed in MG the reason of my issue. Now everything works fine. Thanks everybody for your help!
