### ISSUE TITLE
Desc text about configuring with const and storing pass in DB

### ISSUE THREAD

**Issue by tflight** [awesomemotive/WP-Mail-SMTP#37]
The plugin suggests that if you store the password in the constants/config then the password is not stored in the database. That is true if the password was never stored there, however if you change your configuration and add the password to the constants/config, the password remains in the database.

The message "We highly recommend you setup your password in your WordPress configuration file for improved security" is perhaps misleading as a user may _assume_ the password is subsequently cleared from the database.

My suggestion is to make it more clear to the user that the password is not cleared from the database, or clear it upon discovering the config.

Of course the user can remove the constants, change the password to blank, save changes, and put the constant back. However many users might not think that is necessary and assume the password is no longer in the DB.

**Comment by slaFFik** [comment]
Yeah, makes sense to improve the text. That definitely won't hurt and may be useful.

I will think about the exact wording.
@tflight @lkraav, if you have suggestions - they are highly welcomed.

**Comment by tflight** [comment]
If the constant exists in the config, that is a pretty strong indication the user doesn't want the password in the database. In my opinion, if the password is found in the config **and ** it is seen in the DB, then the plugin should just wipe the one in the DB for you.

If not that approach, I'd at least detect that there is a password in the config and in the DB and alert the user of that condition so they can take whatever action they please. (Perhaps telling the user they can disable the constant, save a blank password, then enable the constant again.)

**Comment by jaredatch** [comment]
> if the password is found in the config **and ** it is seen in the DB, then the plugin should just wipe the one in the DB for you.

I agree that makes sense, we'll see about improving this in the future :)

**Comment by Peneheals** [comment]
> If the constant exists in the config, that is a pretty strong indication the user doesn't want the password in the database. In my opinion, if the password is found in the config **and ** it is seen in the DB, then the plugin should just wipe the one in the DB for you.
> 
> If not that approach, I'd at least detect that there is a password in the config and in the DB and alert the user of that condition so they can take whatever action they please. (Perhaps telling the user they can disable the constant, save a blank password, then enable the constant again.)

It looks like the options are stored forever in the DB after the user has configured them once. If I configure the plugin through the dashboard and after I set up the same settings in the wp-config.php too, the DB still stores the data, however the dashboard clearly shows the **disabled options**, and indicates that the user can not overwrite those options, because they are stored in wp-config.php (or anywhere else).

The correct behaviour should be to empty the similar options in the db somehow.

**Comment by slaFFik** [comment]
I have added much more details to the description of this field, so it will be clear of what to expect and what to do in both situations - when the password is saved in DB and using a constant.
Meanwhile, I'm closing this issue, this will be available in the upcoming WP Mail SMTP release.
