### ISSUE TITLE
Problem with customizing admin page with "wp_mail_smtp_admin_get_pages" filter

### ISSUE THREAD

**Issue by nawawishkid-old** [awesomemotive/WP-Mail-SMTP#38]
I'm trying to customize `Settings` tab in plugin's admin page. The customized page is created by extending `WPMailSMTP\Admin\Pages\Settings` class and overriding `display()` method to display only `From Email` and `From Name` field for custom user role.

I replace original page with the customized page by using `wp_mail_smtp_admin_get_pages` filter like this:

```php
/**
 * Use customized 'Settings' tab of WP Mail SMTP options page.
 */
add_filter('wp_mail_smtp_admin_get_pages', function ($pages) {
    if (current_user_can('administrator')) {
        return $pages;
    }

    include_once __DIR__ . '/WeCom/WPMailSMTPSettingsPage.php';

    $pages['settings'] = new \WeCom\WPMailSMTPSettingsPage();

    return $pages;
});
```

## Plugin version 
1.4.1

## Current Behavior

Nothing changes. The original page still display.

## Expected Behavior

The customized page should be displayed instead of the original one.

## Possible Solution

Since `wp_mail_smtp_admin_get_pages` is applied as a return value of `WPMailSMTP\Admin\Area::get_pages()` method. But inside `WPMailSMTP\Admin\Area::display_current_tab_content()` method (and some other methods), `$this->pages` is used to get admin pages which return only plugin's built-in pages instead of `$this->get_pages()` to use altered pages from `wp_mail_smtp_admin_get_pages` filter. So, I just change `$this->pages` to `$this->get_pages()` like the code below and it works.

```php
/**
	 * Get the current tab title.
	 *
	 * @since 1.0.0
	 */
	public function display_current_tab_content() {

		if ( ! array_key_exists( $this->get_current_tab(), $this->get_pages() ) ) {
			return;
		}

		$this->get_pages()[ $this->get_current_tab() ]->display();
	}
```

## Steps to Reproduce (for bugs)

1. Add new page (extend `WPMailSMTP\Admin\PageAbstract`) or replace built-in page with your custom page (extend `WPMailSMTP\Admin\Pages\<PageName>`)
2. Alter `$pages` variable using `wp_mail_smtp_admin_get_pages` like this:

```php
add_filter('wp_mail_smtp_admin_get_pages', function ($pages) {
    $pages['custom_page'] = new CustomPage(); // Your custom page
    return $pages;
});
```
---

I apologize for my broken English.

**Comment by slaFFik** [comment]
Oh, this is a good thing.
Thank you for the issue and PR! 
This is actually already fixed in the next WP Mail SMTP version (not in this repo), upcoming soon.
I'm not closing issue and PR for now, because I will need to test your exact scenario, but it will be live.

**Comment by slaFFik** [comment]
I've implemented this fix in the upcoming release and closing this issue and PR.
