### ISSUE TITLE
Issue in sending email through "Other SMTP" Option

### ISSUE THREAD

**Issue by mubeeniqbal811** [awesomemotive/WP-Mail-SMTP#4]
Please view the screenshot error message that is appearing after sending email through  "Email Test" tab

## Plugin version 
 WP Mail SMTP   Version 1.2.5

![smpt](https://user-images.githubusercontent.com/40246998/41372103-2936c22e-6f01-11e8-802f-1f45d0c6713d.PNG)

**Comment by slaFFik** [comment]
This information should be provided into the support forum, and not in a development repository, as this is a configuration (site or server) error and not a plugin issue.
