### ISSUE TITLE
Using aliases with Gmail broke eveything

### ISSUE THREAD

**Issue by EmilienCourt** [awesomemotive/WP-Mail-SMTP#40]
Hi,
Having troubles to set up WP Mail SMTP running Wordpress 5.0.3 and WP Mail STMP 1.4.1.
I had set up the Oauth credentials and email to send email from a google group's alias, and everything was working fine.

Just tested today, and it said that the token had been revoked or has expired.

## Plugin version 

1.4.1

## Current Behavior

Tried to regenerate the credentials and to change them in the plugin, could authorize the plugin but it did not work : " There was an error while processing the authentication request. Please try again. "

I double checked and made sure the client-id and client-secret and the redirect urls are right.

I also have a sticked message : 
``
EMAIL DELIVERY ERROR: the plugin WP Mail SMTP v1.4.1 logged this error during the last time it tried to send an email:
    Mailer: Gmail
    {
     "error": {
      "errors": [
       {
        "domain": "global",
        "reason": "required",
        "message": "Login Required",
        "locationType": "header",
        "location": "Authorization"
       }
      ],
      "code": 401,
      "message": "Login Required"
     }
    }
Consider running an email test after fixing it.
``
I tried to delete the plugin folder and to put it back, it kept my old settings.
The "From email" and "From name" fields are greyed and stuck to the alias group.

## Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/22601366/53800649-7df0d180-3f3d-11e9-8e69-4a8e3a23e343.png)

**Comment by slaFFik** [comment]
Hi,

> I also have a sticked message : ... `Login Required` ...

Just go and login in the browser to your google account (log out and login again if you are logged in already right now)

> I tried to delete the plugin folder and to put it back, it kept my old settings.

There is a setting in plugin admin area under "Misc" tab to remove plugin settings on plugin uninstallation (which means deactivate + delete the plugin itself using WordPress Plugins interface).

> The "From email" and "From name" fields are greyed and stuck to the alias group.

This is a limitation of the Gmail integration - it does not allow to overwrite FROM Name/Email and will always send emails from the account you used to create a connection.

**Comment by slaFFik** [comment]
@Emilien942702 
Also, this kind of threads are better posted in a [support forum](https://wordpress.org/support/plugin/wp-mail-smtp/).

**Comment by EmilienCourt** [comment]
Thanks for your answer,
Already tried to log out and login again ...
Can not delete the plugin from the WordPress Plugins interface (not FTP on server).
Alright, but I can not change this parameter, and this is configured with my alias, might be the reason of the bug.

Sorry for that, I can create a thread on the support forum if you prefer
