### ISSUE TITLE
Mailgun integration

### ISSUE THREAD

**Issue by slaFFik** [awesomemotive/wp-mail-smtp#40]
https://github.com/mailgun/mailgun-php

Minimum PHP Version: 5.5.0 - if using a library.
No min PHP version if a POST request is used.

https://documentation.mailgun.com/en/latest/libraries.html#php

Also consider this plugin code (no lib required):

[mailgun.1.5.8.5.zip](https://github.com/awesomemotive/wp-mail-smtp/files/1434231/mailgun.1.5.8.5.zip)

**Comment by jaredatch** [comment]
💯

**Comment by slaFFik** [comment]
Forgot to include a safety check agains PHP version :( 
Easy task though.
