### ISSUE TITLE
Sendgrid: Typo in description

### ISSUE THREAD

**Issue by clarkewd** [awesomemotive/WP-Mail-SMTP#41]
I normally use Google to send emails but was reading over the other built-in options.

On [this line](https://github.com/awesomemotive/WP-Mail-SMTP/blob/47c3e523c8bdff5d7a70f599f732111b91334680/src/Providers/Sendgrid/Options.php#L29) you have the note:

> They provide users 100 free emails per month.

But I think that is actually per day.

**Comment by slaFFik** [comment]
Good catch, you are totally correct as per [their pricing page](https://sendgrid.com/pricing/).
I will update the description for the next plugin release.

Thank you!
