### ISSUE TITLE
Track delivered/opened status of emails for supported providers

### ISSUE THREAD

**Issue by slaFFik** [awesomemotive/wp-mail-smtp#43]
Some providers (like Mailgun, Sendgrid) when email is sent using their API provide a response with an email identifier, that can be used to track the delivered and opened status of a just sent email.

What about saving this info and displaying in admin area somewhere? With or without email content saving. That will be quite a big feature in terms of usefulness and development. But's it's a killer feature too.

**Comment by jaredatch** [comment]
While neat, personally I feel the logging and disabling feature to be more useful.

The opened stats be viewed in the Mailgun/Sendgrid etc dashboard already, and no matter what we would come up with, viewing it in that way will always be better.
