### ISSUE TITLE
message":"Following RFC 1341, section 7.2, if either text/html or text/plain are to be sent in your email: text/plain needs to be first, followed by text/html, followed by any other content.","field":"content","help":null" /* How do I do this if I want duplicate content */

### ISSUE THREAD

**Issue by gurkan-baykan** [awesomemotive/WP-Mail-SMTP#43]
foreach($params as $key => $value ) 
  {
 $data["personalizations"][]["to"][] = ["email" => $value['eposta'] ];
  $data["subject"] = "HELLO";
  $data["from"]=["email"=>"example@gmail.com"];
  $data["content"][]=["type"=>"text/html","value"=>"<h> $value['content']</h>"];
}

**Comment by slaFFik** [comment]
@hurkan-sert 
Could you please format the issue title and description? I don't understand what you are trying to say.
Also, please define your WP Mail SMTP version and mailer (issue template is here for a reason).

**Comment by gurkan-baykan** [comment]
hi slaFFİk,
I'm solved problem,thank
