### ISSUE TITLE
Bottom debug section not visible

### ISSUE THREAD

**Issue by jessquig** [awesomemotive/wp-mail-smtp#45]
## Current Behavior

When running test email, the bottom part of debug message isn't visible: http://cloud.supportally.com/3I3k2C162l36 (Below "The SMTP debugging output is shown below:")

## Expected Behavior

This section should be visible.

## Steps to Reproduce (for bugs)

1. Go to Settings > WP Mail SMTP
2. Send test email and look to bottom of debug output

**Comment by jaredatch** [comment]
I think this is addressed in v1, in which case we close it. Correct @slaFFik ?

**Comment by slaFFik** [comment]
Yes, it's fixed. Displayed only in case of failed test email sending.
