### ISSUE TITLE
GuzzleHttp version conflict

### ISSUE THREAD

**Issue by plenge** [awesomemotive/WP-Mail-SMTP#48]
I updated to 1.4.2, and now my site gives me and error in the logs on send.
I have tried rerolling, but I can't seem to make it reverse the tables in the DB, and forgot to backup before -.- (silly me).

This is the error i get:

```
2019-03-26T15:07:29Z PHP Fatal error:  Uncaught Error: Call to undefined function GuzzleHttp\Psr7\stream_for() in /srv/app/oakdigital/htdocs/www/wp-content/plugins/wp-mail-smtp/vendor/guzzlehttp/psr7/src/Request.php:53
  Stack trace:
  #0 /srv/app/oakdigital/htdocs/www/wp-content/plugins/wp-mail-smtp/vendor/google/apiclient/src/Google/Service/Resource.php(201): GuzzleHttp\Psr7\Request->__construct('POST', Object(GuzzleHttp\Psr7\Uri), Array, '{"raw":"RGF0ZTo...')
  #1 /srv/app/oakdigital/htdocs/www/wp-content/plugins/wp-mail-smtp/vendor/google/apiclient-services/src/Google/Service/Gmail/Resource/UsersMessages.php(197): Google_Service_Resource->call('send', Array, 'Google_Service_...')
  #2 /srv/app/oakdigital/htdocs/www/wp-content/plugins/wp-mail-smtp/src/Providers/Gmail/Mailer.php(94): Google_Service_Gmail_Resource_UsersMessages->send('me', Object(Google_Service_Gmail_Message))
  #3 /srv/app/oakdigital/htdocs/www/wp-content/plugins/wp-mail-smtp/src/MailCatcher.php(105): WPMailSMTP\Providers\Gmail\Mailer->send()
  #4 /srv/app/oakdigital/htdocs/www/wp/wp-includ in /srv/app/oakdigital/htdocs/www/wp-content/plugins/wp-mail-smtp/vendor/guzzlehttp/psr7/src/Request.php on line 53
```

When i try to send a mail.
It worked a few days ago, I am using Google as my sender.
And although every setting is set and authentication seems to have gone through correctly.
I also gives me: 
`You cannot send an email. Mailer is not properly configured. Please check your settings.`
Under the "Email Test" tab.

I have tried reinstalling and erasing table rows in the options table, without luck.

Any help is highly appreciated.

**Comment by plenge** [comment]
Okay, right when i posted this, I tried requiring Guzzlehttp via composer myself, and that seemed to fix the issue.
Did something happen since the plugin suddenly needs this added manually? :) 

This fix, as it fixed the mail plugin, broke Offload S3, so adding it manually is not a viable fix.

**Comment by plenge** [comment]
UPDATE:

WP Offload Media Lite and your plugin is the ones that are messing with each other.
But i really need both plugins :/ 

I'll get back if i find a solution, but if you have any ideas, please let me know :)

**Comment by plenge** [comment]
UPDATE:: 

WP Offload Media namespaces its versions of GuzzleHttp that are bundled with the plugin with a Delicious Brains / WP Offload Media specific namespace and only references those namespaced versions itself.

It looks like WP Mail SMTP does not give its bundled version of GuzzleHttp a uniquely scoped namespace and as such probably accidentally uses WP Offload Media version of the classes as they are presumably loaded first by WordPress.

The chances are the two plugins are using different versions of the GuzzleHttp/Psr7/Request class and WP Mail SMTP is expecting a function to exist that doesn't in WP Offload Media version of the class.

**Comment by hirenshah** [comment]
Is there a fix for this then?

**Comment by slaFFik** [comment]
The issue is multi-layered.

Firstly, different plugins use different versions of the Guzzle lib. One uses the latest, others - older versions.
Secondly, we are indeed not prefixing (namespacing) Guzzle and other libraries inside WP Mail SMTP plugin, yet.

We are working on a fix and will start prefixing everything and after that, no more issues with Guzzle (and other libs) versions compatibility between different plugins will be possible.

I can't provide ETA right now, but the plan is to release this asap.

Meanwhile, I'm closing this issue.

**Comment by jarrodbell** [comment]
Have you got a fix for the scoping yet? This is causing your plugin to fail when other plugins use a namespaced Guzzle library. The other plugins function fine, but this plugin fails.

**Comment by slaFFik** [comment]
Hey @jarrodbell,

We already have a fix and currently testing it internally. The current plan is to release it in mid-September. We need more people updating their sites to WP 5.5 because it has some fixes with flushing PHP OPCache that will help avoid issues on users' sites.
