### ISSUE TITLE
WP Mail SMTP and Mailgun: "Domain not found" when EU region is set

### ISSUE THREAD

**Issue by petterstahre** [awesomemotive/WP-Mail-SMTP#50]
I have the same problem as reported in https://github.com/awesomemotive/wp-mail-smtp/issues/22 but that issue is closed and it seems it wasn't fixed in version 1.4.
(Thanks Jensderond, you saved my day :)

## Current Behavior
When sending mail using Mailgun and Region is set to EU then the debugger reports:
Mailer: Mailgun
Domain not found: xxxx.xxxxx.xx 

## Expected Behavior
Expected the domain to be found on mailgun's EU servers.
The problem is "solved" if I change to US.

## Possible Solution
Also check eu.mailgun.com for the domain

Anyway, thank's for a very neat plugin! / cheers

**Comment by slaFFik** [comment]
> Domain not found

That means your domain is verified for US zone and you need to move it to the EU zone to use EU region.

From Mailgun docs:
> Only a limited amount of account data is replicated globally, giving you a single account from which to manage domains in both the US and the EU.

More information [here (migrate domain)](https://help.mailgun.com/hc/en-us/articles/360007512013-Can-I-Migrate-My-Domain-to-EU-) and [here (general information)](https://www.mailgun.com/regions).
