### ISSUE TITLE
Class 'SMTP' not found

### ISSUE THREAD

**Issue by TimurKelman** [awesomemotive/WP-Mail-SMTP#53]
Trying to send a test email from the plugin configuration page leads to HTTP ERROR 500, no e-mail and following log entry on the server:

```
$sudo tail /var/log/apache2/error.log
...
[Wed May 15 11:53:20.271373 2019] [php7:error] [pid 229480] [client <my ip adress>]
PHP Fatal error:  Uncaught Error: Class 'SMTP' not found in /usr/share/php/libphp-phpmailer/class.phpmailer.php:1495
Stack trace:
#0 /usr/share/php/libphp-phpmailer/class.phpmailer.php(1578): PHPMailer->getSMTPInstance()
#1 /usr/share/php/libphp-phpmailer/class.phpmailer.php(1515): PHPMailer->smtpConnect(Array)
#2 /usr/share/php/libphp-phpmailer/class.phpmailer.php(1301): PHPMailer->smtpSend('Date: Wed, 15 M...', 'Congrats, test ...')
#3 /usr/share/php/libphp-phpmailer/class.phpmailer.php(1180): PHPMailer->postSend()
#4 /usr/share/wordpress/wp-content/plugins/wp-mail-smtp/src/MailCatcher.php(80): PHPMailer->send()
#5 /usr/share/wordpress/wp-includes/pluggable.php(481): WPMailSMTP\\MailCatcher->send()
#6 /usr/share/wordpress/wp-content/plugins/wp-mail-smtp/src/Admin/Pages/Test.php(160): wp_mail(Array, 'WP Mail SMTP: T...', 'Congrats, test ...', Array)
#7 /usr/share/wordpress/wp-content/plugins/wp-mail-smtp/src/Admin/Area.php(403): WPMailSMTP\\Admin\\Pages\\Test->process_post(Array)
#8 /usr/share/wordpress/wp-includes/class-wp-hook. in /usr/share/php/libphp-phpmailer/class.phpmailer.php on line 1495, referer: http://ubuntu/wordpress/wp-admin/options-general.php?page=wp-mail-smtp&tab=test
```

Sending an email via PHP script using `mail($to, $subject, $message, $headers)` does work.

## Versions
Plugin: 1.4.2
PHP: 7.2.15

AFAIK I haven't done anything fancy regarding server configuration, just straight forward LAMP + Wordpress + postfix.

**Comment by slaFFik** [comment]
As I understand, you are using "Other SMTP" mailer, correct?

**Comment by TimurKelman** [comment]
Yes, I'm using "Other SMTP" configured to a local SMTP-server.

**Comment by slaFFik** [comment]
That might be the reason - incorrect local SMTP server configuration.

See this:
```
PHP Fatal error:  Uncaught Error: Class 'SMTP' not found in /usr/share/php/libphp-phpmailer/class.phpmailer.php:1495
```

WordPress and the plugin is using not the phpmailer class that is bundled with WordPress, but something else (the one bundled with SMTP server?).
This is not a plugin code problem, so I'm closing this GH issue.

**Comment by TimurKelman** [comment]
The SMTP-server is a Microsoft exchange server somewhere else entirely. The Wordpress should be just talking to it via the SMTP-protocol. After I disabled this plugin, sending e-mails using "Contact Form 7"-Plugin is actually working without any additional configuration from me.
