### ISSUE TITLE
WooCommerce 'Reply-to' email wrong

### ISSUE THREAD

**Issue by jonasskafte** [awesomemotive/WP-Mail-SMTP#54]
## Plugin version 
1.4.2

## Current Behavior
'Processing order' emails from WooCommerce has the wrong 'Reply-to' email.

Here are my WP Mail SMTP settings:

![Screenshot-2019-06-16-at-15 30 30](https://user-images.githubusercontent.com/11773776/59565472-0b1ee880-904c-11e9-8147-1f0701f5a5b4.jpg)

And here are my WooCommerce settings:

![Screenshot-2019-06-16-at-15 34 02](https://user-images.githubusercontent.com/11773776/59565493-4c16fd00-904c-11e9-8314-604dc566137e.jpg)

Yet WooCommerce emails come through with a different 'Reply-to' address:

![Screenshot-2019-06-16-at-15 36 18](https://user-images.githubusercontent.com/11773776/59565516-94361f80-904c-11e9-8616-ee7ed4aa5ce1.jpg)

## Expected Behavior
That the email address would be as set in WooCommerce and in WP Mail SMTP.

## Possible Solution
I have no idea why this is happening.

## Steps to Reproduce (for bugs)
Perhaps try out the settings I've shared in the screenshots above...?

**Comment by slaFFik** [comment]
I don't see an issue.
`From Email` address and `Reply-To` are two different headers in emails.
WP Mail SMTP and WC both allow you to define `From Email`, but they don't give you an UI to change the `Reply-To`. WP Mail SMTP will reuse any headers that were passed to it, either `From Email` or `Reply-To`.

`Reply-To` is defined somewhere in code.
