### ISSUE TITLE
1.5 update clones initial emails

### ISSUE THREAD

**Issue by Dubaidogfish** [awesomemotive/WP-Mail-SMTP#55]
Version: 1.5

When sending 2 notification emails from a Gravity form submission, 1 to admin and 1 to the user,  v1.5 now sends the admin email twice and misses the user email. 

Expected behaviour as happened before the update, is to get one each.

When sending notifications in WP Job Manager (I'm using Smyles WP Job Manager Emails plugin with this) to alert me to job listings approaching expiry I get eg 30 emails about the expiring jobs, but instead of getting 30 different emails telling me which jobs they are and the link to each of them, I now just get 30 of the same cloned email of the first job it triggered.

Expected behaviour as seen before v1.5 is to get 30 (or whatever number of jobs expiring that day) unique emails.

Have rolled back to 1.42 like other people having same issues: https://wordpress.org/support/topic/duplicate-admin-emails-and-no-user-email-works-1-4-2-broken-1-5-0/

Others seem to report Woocommerce sending duplicate admin emails in similar way to gravity forms issue: https://wordpress.org/support/topic/update-1-5-0-duplicate-woocommerce-admin-emails/

**Comment by slaFFik** [comment]
Hi,

This issue is under investigation. Should be fixed in the v1.5.1 soon.
Could you please tell which mailer are you using?

**Comment by Dubaidogfish** [comment]
Thanks for the quick reply. I'm using it with Mailgun.

**Comment by slaFFik** [comment]
Found the source of the issue, will be fixed in the upcoming 1.5.1.

**Comment by lkraav** [comment]
Thanks. How come https://github.com/awesomemotive/WP-Mail-SMTP/releases aren't up to date?

**Comment by slaFFik** [comment]
We have a different repository for Pro version of the plugin. Their structure differes a bit, and it's currently a manual job to sync these 2 repos, that's why I haven't done that yet, as I was focused on pushing the release. I think I will sync them tomorrow.
