### ISSUE TITLE
Versionless Download (Nearly) Empty

### ISSUE THREAD

**Issue by Akaoni** [awesomemotive/WP-Mail-SMTP#56]
## Plugin version 

1.5.2

## Current Behavior

I download the plugin via the versionless URL (to install latest version to a Docker image):
https://downloads.wordpress.org/plugin/wp-mail-smtp.zip

The downloaded archive only contains `/wp-mail-smtp/readme.txt` however, no actual working files.

## Expected Behavior

It'd be nice if this download worked so I don't have to manually maintain a hard-coded version number in the URL.

## Possible Solution

I think the contents for this file come from trunk. Maybe commit the latest version files in there as well:
https://plugins.trac.wordpress.org/browser/wp-mail-smtp/trunk

**Comment by slaFFik** [comment]
It seems, WordPress.org recently changed the way the zip is built when accessing downloads.wordpress.org/plugin/wp-mail-smtp.zip.
It used to understand the stable version from `readme.txt` and download the one from a proper `tags/*`, but now it's not the case.
An easy solution is to duplicate all the code into `trunk/*` in SVN, but you know, that a duplicate...

**Comment by slaFFik** [comment]
So this is indeed an issue on WP.org side, but I've copied current 1.5.2 tag into `/trunk`, so the URL [downloads.wordpress.org/plugin/wp-mail-smtp.zip](https://downloads.wordpress.org/plugin/wp-mail-smtp.zip) should work soon as expected.

**Comment by Akaoni** [comment]
Awesome, thanks!!
