### ISSUE TITLE
WooCommerce emails doesn't work on checkout but test emails do

### ISSUE THREAD

**Issue by martinrios95** [awesomemotive/WP-Mail-SMTP#57]
## Plugin version
1.6.0

## Current Behavior

Test e-mails work properly, but if you make an action related with WooCommerce, it won't send e-mails to the customer or the WooCommerce admin.

## Expected Behavior

Both type of e-mails should work: testing and WooCommerce related.

## Possible Solution

WooCommerce uses `wp_mail()` to send any type of emails.
I wonder if WP Mail will affect the plug-in's behaviour.

## Steps to Reproduce (for bugs)

1. Install WooCommerce
2. Install WP Mail SMTP
3. Make an order with any product (on any environment, either production or dev)
4. WooCommerce's e-mails won't work.
5. Go to WP Mail SMTP on WordPress admin site and send a test email. It'll work.

**Comment by slaFFik** [comment]
Hi, thanks for the report.
Straightforward cases were tested with Woocommerce. So to investigate I need more details.

1. Which mailer are you using?
1. Is it WordPress or WordPress Multisite?

**Comment by martinrios95** [comment]
Hi, thank you for your answer.
1) We were using PHP's default mailer.
2) WordPress, latest version.

**Comment by slaFFik** [comment]
1. When you use default mailer - you actually don't use WP Mail SMTP functionality at all. Default mailer is left for compatibility, and it does absolutely nothing to improve email deliverability. You should also see a notification in your admin area that says you to configure the plugin. Please choose any other mailer (Sendinblue, Mailgun, Sendgrind)  or Gmail/Other SMTP and configure the plugin to make it work.

Closing the issue as this is a configuration issue, not the plugin issue.

**Comment by martinrios95** [comment]
Hi, I'll try to change the mailer. If I configure the plug-in and it doesn't work, I will write here again on this thread. Thanks :)
