### ISSUE TITLE
Add new "Misc" admin page tab

### ISSUE THREAD

**Issue by jaredatch** [awesomemotive/wp-mail-smtp#59]
The General section looks weird on the Settings tab, especially given that it only contains one item.

Instead, let's create a `Misc` tab, and move the AM Notification opt-out setting to that tab. Having a tab with only 1 options is sorta weird too, but less weird than the former. In the future we can maybe add more settings there if needed.

`Settings | Email Test | Misc`

**Comment by slaFFik** [comment]
![image](https://user-images.githubusercontent.com/282234/33759994-f30d320a-dc0c-11e7-8fee-9b14b7a462e8.png)
