### ISSUE TITLE
Can't select another mailer on mobile

### ISSUE THREAD

**Issue by siccovansas** [awesomemotive/WP-Mail-SMTP#62]
## Plugin version 
1.8.1

## Current Behavior
I can't select a mailer on Android mobile/tablet using either Firefox or Chome. When I want to select a mailer different than the default php mailer, nothing happens.

## Expected Behavior

When I tap on another mailer it should be highlighted in orange and the radio button should be active.

**Comment by sanzeeb3** [comment]
@siccovansas - I am not able to recreate the issue. Could you please switch to the default WordPress themes like Twenty Twenty and confirm the issue? If so, please share more details on your environment.

**Comment by siccovansas** [comment]
@sanzeeb3 I am actually using Twenty Twenty. Some more information about my environment:
- Latest Firefox for Android or Chrome
- Samsung S10
- Android 10

Are there other details I can provide?

(ps: accidentally hit the close issue button, ignore that :D)

**Comment by slaFFik** [comment]
The site theme on the front-end will not have any effect on the WP Mail SMTP plugin admin area.

@siccovansas
I've tested on Google Pixel 2 XL with the latest Android, and wasn't able to replicate the issue.
Can you please record a video and attach it here (or upload somewhere), so we can see that?

**Comment by siccovansas** [comment]
Here I'm clicking on 'Other SMTP', 'Gmail' and 'Sendgrid'. They are highlighted in grey, but the radio button isn't select (neither when I press the radio buttons directly).
![MP4_20200125_001040](https://user-images.githubusercontent.com/696839/73115840-e60c2580-3f0a-11ea-9311-be4481a3fb15.gif)

**Comment by slaFFik** [comment]
Oh, I see now. Thank you for the gif! Those options have the attribute `disabled`.
That means that there are constants in your `wp-config.php` file, that instruct the plugin to set certain values for certain plugin options.

Please open `wp-config.php` and find these lines:
```php
define( 'WPMS_ON', true );
define( 'WPMS_MAILER', 'mail' );
```
You should change the 1st line to `define( 'WPMS_ON', false );`. That will unblock the manual mailer selection.

More information available in [this doc](https://wpmailsmtp.com/docs/how-to-secure-smtp-settings-by-using-constants/).
