### ISSUE TITLE
from email address greyed out, cannot change from email 

### ISSUE THREAD

**Issue by mspace00** [awesomemotive/WP-Mail-SMTP#63]
## Plugin version 
1.8.1

## Current Behavior

From email field greyed out during gmail setup process which was never successfully completed. Moving to Pepipost and now I can't change the from email. Tried deleting and reinstalling plugin but problem persists.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by slaFFik** [comment]
@mspace00 
Pepipost allows changing the FROM email address, while Gmail does not.
You need to switch from Gmail to Pepipost, save the plugin settings (there is a "Save Settings" button at the bottom of the page), and after page reload you will be able to change FROM Email address value.

If that FROM Email field is still blocked for you, that means that it is set as a constant in your `wp-config.php` file, so you open it, find this string `define( 'WPMS_ON', true );` and:
1. either change it to `define( 'WPMS_ON', false );` to disable all plugin constants usage
2. or change your email in this constant: `define( 'WPMS_MAIL_FROM', 'mail@example.com' );`.
