### ISSUE TITLE
Update readme.txt

### ISSUE THREAD

**Issue by jaredatch** [awesomemotive/wp-mail-smtp#65]
This is for non-changelog related updates.

- [x] Update description (will get with @syedbalkhi on this)
- [x] Update FAQs (I'll handle this Monday)

**Comment by jaredatch** [comment]
@slaFFik  Should we get rid of the Upgrade Notice section in the readme.txt?

**Comment by slaFFik** [comment]
No, upgrade notice is used to display a short description of the changes.
`wp-admin/update-core.php::284`:
```php
// Get the upgrade notice for the new plugin version.
if ( isset($plugin_data->update->upgrade_notice) ) {
	$upgrade_notice = '<br />' . strip_tags($plugin_data->update->upgrade_notice);
} else {
	$upgrade_notice = '';
}
```
and then later:
```php
<td class="plugin-title"><p>
	<?php echo $icon; ?>
	<strong><?php echo $plugin_data->Name; ?></strong>
	<?php
		/* translators: 1: plugin version, 2: new version */
		printf( __( 'You have version %1$s installed. Update to %2$s.' ),
			$plugin_data->Version,
			$plugin_data->update->new_version
		);
		echo ' ' . $details . $compat . $upgrade_notice;
	?>
</p></td>
```
So I would leave it for the users convenience.

**Comment by slaFFik** [comment]
This readme question should be deleted:
> Can I use this plugin to send email via Gmail / Google Apps - we use API
> Will this plugin work with WordPress versions less than 2.7? - we are WP 3.0 afaik.

**Comment by slaFFik** [comment]
> * Specify an SMTP host (defaults to localhost).
> * Specify an SMTP port (defaults to 25).

Not correct anymore. This `(defaults to ...)` should be removed. We leave empty values now.

**Comment by syedbalkhi** [comment]
Ok I'm on it guys.

**Comment by syedbalkhi** [comment]
I have updated the readme in the develop branch.

**Comment by jaredatch** [comment]
Much appreciated 💯

**Comment by jaredatch** [comment]
All that is left is to update with a link to our WP.org support policy thread.

I have the copy for that, but need to have all docs complete before I can create it, since we'll be linking to these docs.

Should have everything wrapped up soon.
