### ISSUE TITLE
Multisite Network Admin can't use

### ISSUE THREAD

**Issue by quadcom** [awesomemotive/WP-Mail-SMTP#66]
I have WPSMTP installed in a multisite. The plugin is network active. The admin is available in all of the child sites but it is not available to the network admin. 

I have iThemes security installed on the same multisite, also network active. None of the security notification emails can be sent as only the Network Admin has access to administer iThemes config.

To simplify, WPSMTP is only available to child sites and iThemes is only available to Network Admin.

Note: I have configured the Main sites WPSMTP and those settings do not transfer to the Network Admin level.

## Plugin version 
 1.8.1

## Current Behavior

Configuration for WPSMTP is not accessible by the Network Admin, only child sites. There for you cannot configure SMTP access for the Network Admin.

## Expected Behavior

Allow Network Admin access to configure WPSMTP settings so that the Network Admin is able to send emails.

## Steps to Reproduce (for bugs)

1. Install WPSMTP into a multisite. The admin will be available for child sites but not Network Admin

**Comment by slaFFik** [comment]
Hey @quadcom 

Thanks for your report. We are aware of this issue and it's currently in the works. We plan to greatly improve compatibility with WordPress Multisite installations and provide additional configuration options for power users.
I can't provide you any ETA, but it will be done soon. Just check the changelog with each plugin release :)
