### ISSUE TITLE
Authentication vs Hide Announcement

### ISSUE THREAD

**Issue by slaFFik** [awesomemotive/wp-mail-smtp#68]
## Current Behavior

When you save Hide Announcements (HA) - Authentication option (Auth) is switched to off.
When you save Auth -> On, HA is becoming unchecked.

## Expected Behavior

They should be independent.

## Steps to Reproduce (for bugs)

1. Go to Settings: configure Other SMTP with SendGrid options (important: enable auth).
2. Go to Email Test and test - email is coming.
3. Go to Misc and check HA - save.
4. Go to Settings and check the Auth option - it's off now.
5. Go to Email Test and test - email is NOT coming with an error:
> SMTP server error: MAIL FROM command failed Detail: Unauthenticated senders not allowed

**Comment by slaFFik** [comment]
@jaredatch Can you please try to replicate it locally and confirm that this is not just my weird install?

**Comment by jaredatch** [comment]
Yes, I can replicate it.

It looks like there's a discrepancy between using a bool or 'yes' for the Auth value.
