### ISSUE TITLE
Incorrect Domain Name in Mailgun mailer allows test email to be sent successfully

### ISSUE THREAD

**Issue by ethanchoi812** [awesomemotive/WP-Mail-SMTP#69]
https://secure.helpscout.net/conversation/1156784272/682394/

## Expected Behavior

Incorrect Domain Name in Mailgun mailer should not allow test email to be sent successfully

## Current Behavior

Incorrect Domain Name in Mailgun mailer allows test email to be sent successfully

## Steps to Reproduce

1. Setup Mailgun mailer, but with incorrect domain in the Domain Name field in WP Mail SMTP (see screenshot below)
2. Send Email Test in WP Mail SMTP

## Screenshots

https://a.supportally.com/7CdAC8

**Comment by capuderg** [comment]
Moved the issue to the original repo
