### ISSUE TITLE
Getting are you sure you want to do that error when plugin is activate.

### ISSUE THREAD

**Issue by witchblade32** [awesomemotive/wp-mail-smtp#69]
## Plugin version 
1.0.0

## Current Behavior
when trying to save anything (profile, pages, posts) getting error, you are sure you want to do this, please try again

started immediately after the new version was released. Only occurs when this plugin is active. Site admin works correctly as soon as the plugin is deactivated.  This occurred on multiple sites.

**Comment by jaredatch** [comment]
It's been fixed in a update that's already available. So just updating to the latest (v1.0.2 right now) version will resolve the issue. Sorry about the trouble!
