### ISSUE TITLE
Update 2.1.1 killed website had to deactivate 

### ISSUE THREAD

**Issue by kjburto** [awesomemotive/WP-Mail-SMTP#71]
## Expected Behavior

Updated plugin to 2.1.1 

WordPress version 5.4.1
Current theme: OceanWP (version 1.8.3)
Current plugin: WP Mail SMTP (version 2.1.1) PHP version 7.3.18

## Current Behavior

Updated the plugin and it crashed my website

<details>

```

This plugin failed to load properly and is paused during recovery mode.An error of type E_ERROR was caused in line 44 of the file wp-mail-smtp/vendor/woocommerce/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php. 
Error message: Uncaught  RuntimeException: 
Error saving action: Table  'loftonst_WPRQN._RQN_actionscheduler_actions' doesn't exist in  wp-mail-smtp/vendor/woocommerce/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php:44 
Stack trace: 
#0  wp-mail-smtp/vendor/woocommerce/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(242):   ActionScheduler_DBStoreMigrator->save_action(Object(ActionScheduler_Action),  NULL) 
#1  wp-mail-smtp/vendor/woocommerce/action-scheduler/classes/ActionScheduler_ActionFactory.php(177):   ActionScheduler_HybridStore->save_action(Object(ActionScheduler_Action)) 
#2  wp-mail-smtp/vendor/woocommerce/action-scheduler/classes/ActionScheduler_ActionFactory.php(84):  ActionScheduler_ActionFactory->store(Object(ActionScheduler_Action
```

</details>

**Comment by slaFFik** [comment]
@kjburto 
Action Scheduler (the library that is used by WooCommerce and was implemented in WP Mail SMTP 2.1) was not able to create database tables for some reason.

1. Does the MySQL user that is defined in your wp-config.php file have the `CREATE` permission to create DB tables?
1. How exactly were you updating WP Mail SMTP plugin (step by step please)
1. Could you please list all other active WordPress plugins on your site?

You can try to fix by forcing Action Scheduler to re-create tables.
1. Open `/wp-admin/options.php` page on your site.
1. On that page find options with these names: `schema-ActionScheduler_LoggerSchema`, `schema-ActionScheduler_StoreSchema`, and `action_scheduler_migration_status` -
1. Remove their values (leave them empty), save the changes.
1. Activate on the Plugins page the WP Mail SMTP plugin again.

This will trigger an internal library upgrade routine and that should fix the issue.

**Comment by kjburto** [comment]
1. I am the admin and should have that access.
2. I logged into website and went to Dashboard>Updates, then clicked radio button for updates to all plugins and updated like usual.
3. Existing plugins - CallRail Phone Call Tracking, Elementor, Elementor Pro, Essential Addons for Elementor, Gravity Forms, Gravity Forms Dropbox Add-On, Gravity Forms Zapier Add-on, Happy Elementor Addons, Imagify, Insert Headers and Footers, LoftonQuote, Rank Math SEO, Wordfence Security, WP Cloud Plugin Out-of-the-Box (Dropbox), WP Mail SMTP, WP Rocket

I can only find  schema-ActionScheduler_LoggerSchema  &  schema-ActionScheduler_StoreSchema and cannot find action_scheduler_migration_status I am not sure if I should follow this procedure for the two options if the other is not available?

**Comment by slaFFik** [comment]
@kjburto 

1. I'm talking about MySQL user, not WordPress user. Those are credentials used to create new tables in your database. 
1. Got it, thank you.
1. Thank you for the list.

Regarding clearing those options - yes, please proceed with `schema-ActionScheduler_LoggerSchema` and `schema-ActionScheduler_StoreSchema`.

**Comment by kjburto** [comment]
Okay I have cleared those and reactivated the plugin and all seems good now. Thank you

**Comment by slaFFik** [comment]
Awesome, thank you for your collaboration!
