### ISSUE TITLE
PHP Notice using Default mailer

### ISSUE THREAD

**Issue by jaredatch** [awesomemotive/wp-mail-smtp#72]
```
AH01071: Got error 'PHP message: PHP Notice: Undefined index: encryption in /wp-content/plugins/wp-mail-smtp/src/Processor.php on line 72\n'
```

That is this line:
`phpmailer->SMTPSecure = $options[ $mailer ]['encryption'];`

I believe the SMTPSecure detection should be adjusted to:

```
if ( isset( $options[ $mailer ]['encryption'] ) ) {
	if ( 'none' === $options[ $mailer ]['encryption'] ) {
		$phpmailer->SMTPSecure  = '';
	} else {
		$phpmailer->SMTPSecure = $options[ $mailer ]['encryption'];
	}
}
```

Note that `SMTPAutoTLS` has been removed this that will be handled separately as discussed in #70

**Comment by jaredatch** [comment]
Here's the .org link for reference https://wordpress.org/support/topic/v-1-0-0/page/2/#post-9776710

**Comment by slaFFik** [comment]
The fix makes sense to me.
