### ISSUE TITLE
Uncaught RuntimeException Unclosed quotation mark after the character string ' after upgrade to 2.1.1 version

### ISSUE THREAD

**Issue by JulioNobre** [awesomemotive/WP-Mail-SMTP#73]
## Introduction
After todays upgrade to version 2.1.1, WP Mail SMTP plugin started to fail.

## Failure symptoms 
Whenever I access my Wordpress intranet site I started to get the following exception

**Fatal error**: Uncaught RuntimeException: Error saving action: Error saving action: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]**Unclosed quotation mark after the character string '**O:30:"ActionScheduler_SimpleSchedule":2:{s:22:"'. in C:\inetpub\wwwroot\Eureka\wp-content\plugins\wp-mail-smtp\vendor\woocommerce\action-scheduler\classes\migration\ActionScheduler_DBStoreMigrator.php:44 Stack trace: #0 C:\inetpub\wwwroot\Eureka\wp-content\plugins\wp-mail-smtp\vendor\woocommerce\action-scheduler\classes\data-stores\ActionScheduler_HybridStore.php(242): ActionScheduler_DBStoreMigrator->save_action(Object(ActionScheduler_Action), NULL) #1 C:\inetpub\wwwroot\Eureka\wp-content\plugins\wp-mail-smtp\vendor\woocommerce\action-scheduler\classes\ActionScheduler_ActionFactory.php(177): ActionScheduler_HybridStore->save_action(Object(ActionScheduler_Action)) #2 C:\inetpub\wwwroot\Eureka\wp-content\plugins\wp-mail-smtp\vendor\woocommerce\action-scheduler\classes\ActionScheduler_ActionFactory.php(84): ActionScheduler_ActionFactory->s in C:\inetpub\wwwroot\Eureka\wp-content\plugins\wp-mail-smtp\vendor\woocommerce\action-scheduler\classes\migration\ActionScheduler_DBStoreMigrator.php on line 44

O site está com problemas técnicos. Por favor, verifique o email de administrador do site para obter instruções.

## What we already know
Tracing our **SQL Server database** commands using **Microsoft SQL Server Profiler** I was able to assess that sql command **LIMIT** was causing an exception. Further digging on "LIMIT" expression among PHP plugin scripts, led me to a conclusion: **LIMIT** clause is not supported on **Microsoft SQL Server**, although there is an equivalent **TOP** clausule. Therefore, it seems the plugin (wp-mail-smtp.php) is sending sql based on **MySQL** language instead of **MSSQL**.

Deactivating WP-Mail-SMTP plugin, my intranet wordpress site got alive again.

Can you help me?

**Comment by slaFFik** [comment]
Hello. 
I feel sorry that you are experiencing this issue, although it's out of our control.
Our plugin is using Action Scheduler library, developed by Automatic, under the hood. Only MySQL is supported properly by WordPress, WP Mail SMTP and Action Scheduler at this time. 

I would suggest you to reply in this thread to notify library authors that they might need to start considering MSSQL support: https://github.com/woocommerce/action-scheduler/issues/557

Have a nice day.
