### ISSUE TITLE
Sanitizing SMTP passwords

### ISSUE THREAD

**Issue by jaredatch** [awesomemotive/wp-mail-smtp#74]
On save passwords are sanitized with `sanitize_text_field()`.

I see a few potential problems with this.

> Converts single < characters to entities
> Removes line breaks, tabs, and extra whitespace

Depending on the user's password and service, it's may be possible their password begins with or ends in a space. 

In addition to this, it's common for random/secure passwords generated to contain `<` and `>`.

Lastly, I can't recall off the top of my head but we need to see if this also may affect Google/SG/MG tokens/API keys.

**Comment by slaFFik** [comment]
Tokens won't be affected. We also do not process auth_code/access_token at all. 
I think, we can safely rely on `update_option()` saving logic and ignore these values from sanitizing:
- `pass`
- `api_key`
- `domain`
- `client_id`
- `client_secret`
- `auth_code`
- `access_token`

I will push a simple PR for that.
