### ISSUE TITLE
WordPress 5.5 alpha deprecates class-phpmailer.php, breaks sending functionality

### ISSUE THREAD

**Issue by pkarjala** [awesomemotive/WP-Mail-SMTP#74]
## Expected Behavior
When running wp-mail-smtp in WordPress 5.5, it should have normal functionality.

## Current Behavior
When running wp-mail-smtp in WordPress 5.5, it throws a warning when WP_DEBUG is on that `class-phpmailer.php` is being deprecated, as per the following warning:

```
Deprecated: class-phpmailer.php is <strong>deprecated</strong> since version 5.5.0! Use wp-includes/PHPMailer/PHPMailer.php instead. The PHPMailer class has been moved to wp-includes/PHPMailer subdirectory and now uses the PHPMailer\PHPMailer namespace. in /var/www/html/wp-includes/functions.php on line 4924
--


1 | 0.0011 | 405688 | {main}( ) | .../admin.php:0
2 | 0.0012 | 406168 | require_once( '/var/www/html/wp-load.php' ) | .../admin.php:34
3 | 0.0024 | 421240 | require_once( '/var/www/html/wp-config.php' ) | .../wp-load.php:37
4 | 0.0026 | 423088 | require_once( '/var/www/html/wp-settings.php' ) | .../wp-config.php:95
5 | 0.1124 | 3532680 | do_action( ) | .../wp-settings.php:416
6 | 0.1124 | 3533056 | WP_Hook->do_action( ) | .../plugin.php:478
7 | 0.1124 | 3533056 | WP_Hook->apply_filters( ) | .../class-wp-hook.php:311
8 | 0.1756 | 4279128 | WPMailSMTP\Core->replace_phpmailer( ) | .../class-wp-hook.php:287
9 | 0.1756 | 4279152 | WPMailSMTP\Core->replace_w_fake_phpmailer( ) | .../Core.php:565
10 | 0.1756 | 4279152 | spl_autoload_call ( ) | .../Core.php:580
11 | 0.1756 | 4279200 | {closure:/var/www/html/wp-content/plugins/wp-mail-smtp/wp-mail-smtp.php:16-61}( ) | .../Core.php:580
12 | 0.1774 | 4298656 | require_once( '/var/www/html/wp-content/plugins/wp-mail-smtp/src/MailCatcher.php' ) | .../wp-mail-smtp.php:59
13 | 0.1776 | 4298928 | require_once( '/var/www/html/wp-includes/class-phpmailer.php' ) | .../MailCatcher.php:7
14 | 0.1776 | 4299040 | _deprecated_file( ) | .../class-phpmailer.php:11
15 | 0.1776 | 4299520 | trigger_error ( ) | .../functions.php:4924
```

In addition, attempting to send a test email using a correctly configured, previously working setup on WordPress 5.4 before upgrading WordPress to 5.5 alpha results in an error being thrown as follows:

```
Fatal error: Uncaught Error: Class 'PHPMailer\PHPMailer\SMTP' not found in /var/www/html/wp-includes/PHPMailer/PHPMailer.php on line 1821
--

1 | 0.0011 | 405688 | {main}( ) | .../admin.php:0
2 | 0.4793 | 6272144 | do_action( ) | .../admin.php:173
3 | 0.4793 | 6272520 | WP_Hook->do_action( ) | .../plugin.php:478
4 | 0.4793 | 6272520 | WP_Hook->apply_filters( ) | .../class-wp-hook.php:311
5 | 0.4889 | 6557616 | WPMailSMTP\Admin\Area->process_actions( ) | .../class-wp-hook.php:287
6 | 0.4890 | 6557616 | WPMailSMTP\Admin\Pages\TestTab->process_post( ) | .../Area.php:773
7 | 0.4891 | 6575008 | wp_mail( ) | .../TestTab.php:172
8 | 0.4915 | 6619392 | WPMailSMTP\MailCatcher->send( ) | .../pluggable.php:494
9 | 0.4917 | 6627160 | WPMailSMTP\MailCatcher->postSend( ) | .../MailCatcher.php:88
10 | 0.4917 | 6627160 | WPMailSMTP\MailCatcher->smtpSend( ) | .../PHPMailer.php:1601
11 | 0.4917 | 6627608 | WPMailSMTP\MailCatcher->smtpConnect( ) | .../PHPMailer.php:1858
12 | 0.4917 | 6627608 | WPMailSMTP\MailCatcher->getSMTPInstance( ) | .../PHPMailer.php:1942
```

This is a fresh WordPress install, upgraded from 5.4 to 5.5, no other plugins or themes installed.  This is on the WordPress 5.5-alpha-48236 commit; the issue may be resolved by the time 5.5 is released, but it should be given attention ahead of that time.

## Possible Solution
Not sure, but this is likely related to https://core.trac.wordpress.org/ticket/41750 which is tracking the changes to the PHPMailer class and the deprecation of the old class.

## Steps to Reproduce
1.  Install WordPress 5.5 alpha
2.  Install wp-mail-smtp 2.1.1
3.  Configure wp-mail-smtp 2.1.1
4.  Enable `WP_DEBUG`
5.  Attempt to send a test email.

See also https://wordpress.org/support/topic/wordpress-5-5-deprecates-functionality/

**Comment by capuderg** [comment]
Hi @pkarjala,

thank you again for providing detailed information about this issue.

As [answered here](https://wordpress.org/support/topic/wordpress-5-5-deprecates-functionality/),  we will prepare the plugin to work with WP 5.5 when it releases. We have an internal GH issue already opened for this issue, so I'll be closing this one.

We do really appreciate your time to let us know about this issue. Thanks!
