### ISSUE TITLE
Debug output: make it clear what should be copied

### ISSUE THREAD

**Issue by slaFFik** [awesomemotive/wp-mail-smtp#75]
I see users are skipping `SMTP Debug` section, would be nice to help them understand that we need that info as well.

Consider adding backticks, so when user will copy-paste in forum topic - it will be properly marked as code section.

**Comment by slaFFik** [comment]
`@jaredatch` test

**Comment by jaredatch** [comment]
Reopening this with some more thoughts.

The Gmail SMTP plugin also includes the following in their default debug logs, I suspect in some cases it may be helpful and perhaps we should consider including as well.

```
openssl: Available
allow_url_fopen: Enabled
stream_socket_client: Available
fsockopen: Available
cURL: Available
cURL Version: 7.54.0, OpenSSL/1.0.2k
```

Currently when using Google it also includes
```
Host: localhost
Port: 25
SMTPSecure: NULL
SMTPAutoTLS: bool(true)
SMTPAuth: bool(false)
```

I believe this should be omitted with non-SMTP/Pepipost mailers as it's not relevant.

Lastly, for non-SMTP mailers, specifically Google, is there other helpful debug log type items we can include in its place? Right now when Google doesn't send, we have no provide no errors or additional information at all.

**Comment by slaFFik** [comment]
All those extra debug info will be part of the #87. In this task I will adjust the debugging output based on the mailer (so no need in PHPMailer data for non-smtp integrations).
