### ISSUE TITLE
Gmail: exception is thrown on PHP 5.6 with bad local certificate

### ISSUE THREAD

**Issue by slaFFik** [awesomemotive/wp-mail-smtp#76]
## Plugin version 

1.0.2

## Current Behavior

Screenshot: https://ppt.cc/fY16Bx@.png
Thread: https://wordpress.org/support/topic/1-0-2-gmail-auth/#post-9778659
Local WAMP install, xDebug enabled, PHP 5.6.

## Expected Behavior

Fail silently, catch the exception.

## Possible Solution

try/catch.

**Comment by slaFFik** [comment]
Replicated the problem. No need in SSL installed on a domain.

**Comment by jaredatch** [comment]
Looks good to me. In the near future we need a way to show these error messages to the user (and to us) as that will help us debug and accurately describe the issue to the user.

**Comment by slaFFik** [comment]
Will be part of #87
