### ISSUE TITLE
Does NOT work: remove ALL WP Mail SMTP data upon plugin deletion

### ISSUE THREAD

**Issue by mothernateur** [awesomemotive/WP-Mail-SMTP#76]
## Expected Behavior

When I check the box to delete all data when the plugin is uninstalled, none of my information should be remembered when I re-install. Settings/General fields should be blank.

## Current Behavior

When I re-install, the information that I previously entered before uninstalled, is remembered and already filled in in the fields. Because of this, I am unable to continue setup, after receiving an Error 401: deleted_client The OAuth client was deleted.
I deleted the project in Google, because the setup was not done correctly, and because the plugin is remembering the old project, I can not complete set up.
I also can not restore the old project in Google, because the page won't load for some reason.

## Possible Solution

Possible solution, would be to be able to uninstall the app and all data/information/field answers are deleted and forgotten, so that I could re-install it and start completely over.

## Steps to Reproduce

1.
2.
3.
4.

## Screenshots

<img width="1265" alt="Screen Shot 2020-07-11 at 12 18 08 PM" src="https://user-images.githubusercontent.com/68159479/87228665-b940b300-c370-11ea-9dae-51366ce6db55.png">
<img width="386" alt="Screen Shot 2020-07-11 at 12 18 40 PM" src="https://user-images.githubusercontent.com/68159479/87228675-c9589280-c370-11ea-8368-7a8d18000b45.png">

**Comment by capuderg** [comment]
Hi @mothernateur,

could you please tell us some basic site info:
- PHP version
- MySQL version
- WP version
- are you using a WP MultiSite (network)?
- a list of all active WP plugins

Is your hosting using some external DB caching system?

I just tested out the uninstall process on a fresh WP installation and the Gmail setup that I had configured was successfully removed and upon re-installing our plugin it had the default plugin settings (no prior settings were remembered).

We have to figure out why this is not working for you. Since you also experience issue #77, I suspect there is some DB caching causing this issue.

Take care!

**Comment by mothernateur** [comment]
Morning,
Please bear with me, as I am essentially a "newbie" to tech/designing sites.
I don't know how to find out my MySql version, but my site is being designed on WordPress by me.

WordPress Version: 5.4.2
PHP: 7.3

I am assuming by "WP Multisite", you're asking if I have more than one site on WordPress? If so, then yes. I have another site also on WP which I created 2 years ago, same theme and same plugins, which also uses WP Mail SMTP, and that set up was just fine. I had 2 others as well (again, same themes and plugins) which I set up as well with no issues, but I recently deactivated those sites.
The only difference would obviously be that I used different emails for the mail setup. I also never had to delete this plugin on those sites, because I did the setup correctly on the first try.

No external hosting, everything is on WordPress.

Current list of active plugins include:
- Akismet Anti-Spam
- AMP
- CoBlocks
- Full Site Editing
- Gutenberg
- Jetpack by WordPress.com
- Layout Grid
- Page Optimize
(The above were already installed and active upon creating an account)
(The below are the plugins I installed)
- WPForms 
- Elementor

**Comment by mothernateur** [comment]
Now another update... Since my last message from this morning, I have deleted the plugin, cleared my cache and data, logged out of WordPress, restarted my computer, opened a new window, logged back into all accounts, installed WP Mail SMTP... and this time only half of the fields were remembered. So I went through the whole entire process with making a new project to get a new ID/Secret. When I click Save, the page refreshes and at the top, I am notified that it's been saved... however, when I scroll down, half of the fields are blank again (including ID and Secret), and the mailer is back set at Default, instead of Google/Gmail. So it didn't save it.

-------- Below is what I typed on a help forum, not sure if this will help at all...
"I was setting up the plugin (which I’ve done 3 times before for other sites with WP Mail SMTP for Gmail, so I’m familiar with the process), but I wasn’t really paying attention to what I was doing and didn’t get the right ID or Secret, because when the 2nd tab opened, it was for another email account. (I didn’t realize this until I tried the 3rd setup.)

So I tried to start over with a totally new project. That didn’t work.

I deleted both of those projects (then I found out it takes 30 days to complete for a recovery time period), started another new one, but that didn’t work either. This time I got a: Authorization Error 401: deleted_client The OAuth client was deleted.

I went to the plugin setting and tapped Misc, I checked the “delete all info when deleted” box, I uninstalled the plugin from my site, and re-installed it… but I noticed my info was still saved when I opened it. I deleted the ID/Secret fields, created a new project, entered new ID/Secret, and that didn’t work. Same 401 error.

When I un-deleted the project, I was able to save and confirm, pick the email account, and made it all the way to the "This App isn't verified" page. I clicked Advance and bypassed it, but when I tried to do a test email, the button was not highlighted and the courser turned into an X, because of some reason that I forgot. Ugh!!
Help!!!!"

**Comment by capuderg** [comment]
By WP multisite I mean this: https://www.wpbeginner.com/glossary/multisite/, but from what you described, I don't think you are using a multisite version of WP :) You have several standalone WordPress installations...

Is this site that you are working on accessible only locally (you are developing this site locally before it will be hosted on a server)?

> ...time only half of the fields were remembered

Which fields were still populated? If the Gmail ID and secret were empty and the "From Email" and "From Name" was populated, that's OK (expected).

Is it possible, to disable all plugins except the WP Mail SMTP and then try to save the plugin settings? If you don't want to or can't disable all of them, then please at least disable the "Page Optimize" and "Jetpack". I would like to eliminate the possibility of a 3rd party plugin causing this issue.

Let me know how it goes.

Take care!

**Comment by mothernateur** [comment]
I read the link that you provided, and I don't think it is multisite. However, all 5 of my sites are under one account, but they different domains and they aren't linked to each other. 2 of them used to have the same theme and plugins, both had SMTP set up without any issues, but different emails. I didn't not have any issues setting up the SMTP for those. This site now has the same theme and plugins, different email.

From email and from name were the two that were populated, the other fields were empty. However, when the problem first started, all fields were populated upon re-installing, until yesterday. So this is new.
After I report this problem on this site, all fields were empty after re-installing, but nothing would save.
Now Email and Name are populated, but nothing would save.

I deactivated all plugins (however it is not possible to deactivate Jetpack), and after re-installing, Email and Name is still populated and I still can not save. When I click save, the page refreshes, I see the notification that it was saved at the top of the screen, but when I scroll down, all of the other fields are empty again and the mailer is set back at default.

**Comment by capuderg** [comment]
Where are you hosting this site (are you working on it locally or is it hosted on a server, which hosting company)?

Could you please try selecting the "Other SMTP" mailer in the plugin settings, change the "SMTP Host" to "test.mail.com" and save the settings. Did the settings saved this time or did it also jump back to the default settings (Default (none) mailer)?

If you have access to PHP error logs on your server, please also check those out (you can contact your hosting support and they should be able to help you out with these logs). Maybe there are some error messages that would point us in the right direction.

Something is preventing your site from saving the plugin settings, we just need to find out what it is...

Take care!

**Comment by mothernateur** [comment]
I am hosting on WP... everything is on WP. I was able to solve the issue, so I no longer need help. Thank you for everything!

**Comment by capuderg** [comment]
Hi @mothernateur,

that's great! :)

Could you please share with others what was the issue and how you fixed it?

Maybe we can even improve our plugin so we could prevent this issue...

Have a nice day!
