### ISSUE TITLE
Update from my previous bug issue, now it won't save anything!

### ISSUE THREAD

**Issue by mothernateur** [awesomemotive/WP-Mail-SMTP#77]
## Expected Behavior

When I fill in all the fields and click save, it should save, and I should then see a button that says, "Allow plugin to send emails using your Google account". And then everything should be confirmed and set up is complete.

## Current Behavior

When I fill in all the fields and click save, the page refreshes and all the fields are empty. So now nothing is getting saved (which is the complete opposite from the bug ticket I sent a few hours ago. Then, the plugin would save everything, even after I checked the box to clear all data after I've deleted the plugin (which I tried several times)... it would still remember/save the fields. Therefore, I could not start the setup over and get a new Secret/ID). I kept getting the 401 error.
But now, nothing is saving.

## Possible Solution

At this point, I have no clue, hahahaha!

## Steps to Reproduce

1. Fill in all fields
2. Click save
3. Page will refresh, and all fields will be empty
4.

**Comment by capuderg** [comment]
Let's discuss both of these issues you are having in the first GH issue you opened.

I'm closing this issue for now, since I think whatever was causing the issue #76, is probably causing It for this issue as well.
