### ISSUE TITLE
Document Filter and Action changes

### ISSUE THREAD

**Issue by aidik** [awesomemotive/WP-Mail-SMTP#79]
## Expected Behavior
It would be nice if you would give a little bit more love to documentations of changes to Filters and Actions. A short line in release notes can go a long way.

## Current Behavior
Filters and Actions are kept a mystery. 

## Screenshots
Not applicable.

Thank you in advance for considering my proposition & Thank you for a great plugin!

**Comment by slaFFik** [comment]
Hello @aidik

Are you talking about mentioning which filters/actions were added in new releases? We basically add them in a new code when we see they might be useful.

**Comment by aidik** [comment]
Hi Slava (@slaFFik),

yeah, that would be ideal. With the WP 5.5 there is a little schism where some filters are working only on specific versions of WP. For example `wp_mail_smtp_providers_mailer_get_body` would not be triggered at all on WP 5.5

You have an extensive support for filters/actions and as you said you are indeed adding them everywhere it makes sense and might be useful. It is a pity, that users would not learn about them unless they dive into the code.

**Comment by capuderg** [comment]
Hi @aidik,

so you hooked to `wp_mail_smtp_providers_mailer_get_body` and it's not triggering on WP 5.5, but it did on WP 5.4?

Which mailer are you using? I would like to look into this issue.

**Comment by aidik** [comment]
@capuderg other mailer. I believe that this code is used instead: https://github.com/awesomemotive/WP-Mail-SMTP/blob/master/src/MailCatcherV6.php

**Comment by capuderg** [comment]
Hi @aidik,

the filter you mentioned: `wp_mail_smtp_providers_mailer_get_body ` is here: https://github.com/awesomemotive/WP-Mail-SMTP/blob/master/src/Providers/MailerAbstract.php#L219

And it does not trigger in WP 5.5 as well as WP 4.9.

The "Other SMTP" mailer uses this method to send an email in WP 5.5: https://github.com/awesomemotive/WP-Mail-SMTP/blob/master/src/MailCatcherV6.php#L36 and this one for older WP versions: https://github.com/awesomemotive/WP-Mail-SMTP/blob/master/src/MailCatcher.php#L42

Take care!

**Comment by aidik** [comment]
@capuderg yeah I figured that out before. That is ok, I was just looking for some documentation or mentions on release notes. As I was saying just one line: "`wp_mail_smtp_abc` is deprecated, use `wp_mail_smtp_xzy` instead." In release notes would make it easier. It is just a suggestion.

**Comment by capuderg** [comment]
Hi @aidik,

we try not to remove or change the existing filters/actions. But we'll try to include that info if it ever comes to that in the changelog or in some other way.

Thank you for your feedback, we appreciate it!
