### ISSUE TITLE
Google API dependency is causing flags with security scanners

### ISSUE THREAD

**Issue by jaredatch** [awesomemotive/wp-mail-smtp#79]
## Plugin version 
1.0.2

## Current Behavior
Using WP Mail SMTP with WordFence or VaultPress (and probably others) security plugins/services causes issues. These issues are caused by the `phpseclib/Crypt` library that's included as a dep of the Google API.

WordFence: https://wordpress.org/support/topic/wordfence-critical-severity-warning/
VaultPress: https://wordpress.org/support/topic/vaultpress-security-alert-2/

## Expected Behavior
Using WP Mail SMTP should not trip scanners.

## Possible Solution
There is a good chance the part of the Google API we use does not need or use this dependency, in which case it could be removed.

![2017-12-13 18 20 35](https://user-images.githubusercontent.com/282234/33951755-83c06c16-e038-11e7-8a18-2b0a21c93c4d.png)

**Comment by slaFFik** [comment]
@jaredatch we actually need to test against WordFence and Vaultpress.

**Comment by slaFFik** [comment]
@jaredatch Might be a good idea to notify both plugins about false-positives in a popular https://packagist.org/packages/phpseclib/phpseclib library.

**Comment by slaFFik** [comment]
Tested against 1.0.2 (which was in question for this ticket).
WordFence free version doesn't report the issues with the plugin. So it's a premium-only feature, that I can't test. Same for Vaultpress (premium-only).
Thus, I can't reliably say that 1.0.3 will not be flagged.

**Comment by jaredatch** [comment]
Well regardless it's a step in the right direction :)
