### ISSUE TITLE
Remove Database Table With Confirmation

### ISSUE THREAD

**Issue by hlaporthein** [awesomemotive/WP-Mail-SMTP#82]
I think that would be great if you add database table removed after uninstall with confirmation deleting data. 

I think when website administrator remove the plugins, database table also should remove?

**Comment by slaFFik** [comment]
Hey @hlaporthein 

It's already possible to remove tables and all plugin data from the database on plugin uninstall (when it's deleted). Just go to WP Mail SMTP > Settings > Misc page, and check the "Uninstall WP Mail SMTP" option.

After that when plugin is deleted it will remove all tables with `wp_wpmailsmtp_*` prefix and all of its options etc.

**Comment by hlaporthein** [comment]
Hello @slaFFik , Here is video screencast, why it is not working.  https://drive.google.com/file/d/1jKH5ybzusaXDje2ibMn-rxqSP8EDabuX/view?usp=sharing

**Comment by slaFFik** [comment]
@hlaporthein Thanks for the video, now I see where the confusion is.

The tables that are left are all part of the Action Scheduler library, which is indeed bundled into the WP Mail SMTP plugin. But this library is very popular and is used in lots of other plugins, including WooCommerce.
This library creates its own tables only once and they are used by all other activated plugins that have this Action Scheduler library bundled. If in the WP Mail SMTP plugin we remove them - we will break WooCommerce, for example.

So those tables should be left and can't be deleted, there is no reliable and easy way to determine whether the library tables are used by some other plugin or not, so we are leaving them as is.

I hope that clarifies the confusion.
