### ISSUE TITLE
PHP Notice: Undefined index: encryption

### ISSUE THREAD

**Issue by superjunky** [awesomemotive/wp-mail-smtp#83]
Hey hi,

After the latest update (1.0.2), I get these PHP notices in local-dev log:

`Undefined index: encryption in /Users/robbie/Projects/photosessions.nl/wp/wp-content/plugins/wp-mail-smtp/src/Processor.php on line 72`

When you have a moment to spare, maybe you can look into it.

**Comment by jaredatch** [comment]
Hey @superjunky,

Thanks for the report! This should be fixed in the next version, which hopefully will go out tomorrow :)

See https://github.com/awesomemotive/wp-mail-smtp/issues/72

Thanks!
