### ISSUE TITLE
Code error on pluggin 'WP Mail SMTP'

### ISSUE THREAD

**Issue by greyhorsepilates** [awesomemotive/WP-Mail-SMTP#83]
## Expected Behavior

Pluggin should work and send emails to current and new clients that signup.

## Current Behavior

After investigation, we have found that there is be an error on the code of the plugin `WP Mail SMTP`.
Upon reviewing our logs, we found the message below:

```
Fatal error: Namespace declaration statement has to be the very first statement or after any declare call in the script in wp-mail-smtp/src/MailCatcherInterface.php on line 3
```

We proceeded to deactivate the aforementioned plugin and now the website is working.
We would suggest you contact your developer or the plugin's Support in case you want to further utilize it on your website.

**Comment by capuderg** [comment]
Hi @greyhorsepilates,

this is a strange issue and it usually occurs on corrupted files. Maybe it got corrupted while installing/updating?

Could you please check the content of that file on your server: `/imovepilates-www/wp-content/plugins/wp-mail-smtp/src/MailCatcherInterface.php`? Is there any whitespace or other charcters before the `<?php` tag or around it (before the `namespace WPMailSMTP;` code)?

You could also try to delete the plugin and install it again.

Take care!

**Comment by slaFFik** [comment]
Closing this issue for the lack of activity.
