### ISSUE TITLE
Retry 3 times sending on temporary connection errors

### ISSUE THREAD

**Issue by xihh87** [awesomemotive/WP-Mail-SMTP#84]
## Expected Behavior

When the SMTP server is temporarily unavailable, retry sending the message after some timeout.

## Current Behavior

Sending email fails when for any reason the SMTP server is temporarily unavailable.

## Screenshots

![2020-09-16-193035](https://user-images.githubusercontent.com/16003955/93405660-31d15d80-f853-11ea-82dc-3cba4df190c2.png)

**Comment by capuderg** [comment]
Hi @xihh87,

thank you very much for your feedback, we really appreciate it. I have added this to our feature request lists to consider when we plan for the future releases.

Thank you and have a nice day!
