### ISSUE TITLE
opens new page

### ISSUE THREAD

**Issue by tc2u4me** [awesomemotive/WP-Mail-SMTP#85]
## Expected Behavior

It should activate so I can get to settings

## Current Behavior

When I click activate, the plugin takes me to my home page. Can't activate. Uninstalled, reinstalled, same thing.

**Comment by capuderg** [comment]
Hi @tc2u4me,

I just tested plugin activation and it works OK on my testing site. Also, if this would be a general error a lot of people would report it. I think something else is causing this issue on your site.

Does this happen for any other plugin?

Could you please enable WP debugging with logging? [Here are the instructions](https://www.wpbeginner.com/wp-tutorials/how-to-set-up-wordpress-error-logs-in-wp-config/). Then try to activate the plugin again and see if there will be any errors logged in `wp-content/debug.log` file on your server.

Could you also let us know which WP and PHP versions your site is using?
And what other plugins you have active?

Take care!

**Comment by slaFFik** [comment]
Closing this issue for the lack of activity.
