### ISSUE TITLE
Improve debugging/reporting

### ISSUE THREAD

**Issue by jaredatch** [awesomemotive/wp-mail-smtp#87]
#### Google integration 

The Google integration is proving popular. We're getting a fair amount of issues reported with it through .org, documentation comments, and in HelpScout.

Improving this the reliability of this integration, or at least improving the debugging, needs to be a our top priority moving forward after `1.1.0`.

Slightly related to #75.

## Plugin version 
1.0.2

## Current Behavior
Right now if there if the user has an issue with the Google integration, we don't have any insight on why or what. Since we don't know really know what went wrong, it's hard for us to accurately help the user resolve the issue (eg was it user error, server issue, firewall, etc).

## Expected Behavior
We need to detect and show any errors or related items. If there was an error/exception setting up the connection, we need to show it to the user so they can provide it to support. Similarly, we need to provide logs/errors when a user sends a test Google email and nothing happens (right now our current logs don't display anything useful).

For testing, we have access to most common hosts (HostGator, WPE, LiquidWeb, Pagely, Bluehost, Dreamhost, etc). 

Once we get some better reporting/logging in place, we should test the integration on all the major hosts we have access to. This would allow us to find any issues, determine if there is a work around that can be done on our end, and if not then be able to alert those customers the way they can get it working (eg you need to contact X host to disable firewall].

## Possible Solution
TBD

**Comment by slaFFik** [comment]
Will be done in parallel with #54

**Comment by slaFFik** [comment]
Lots of improvements were done in this field.
