### ISSUE TITLE
Investigate BCC support for all providers

### ISSUE THREAD

**Issue by slaFFik** [awesomemotive/wp-mail-smtp#89]
## Plugin version 
1.0.2

## Current Behavior

BCC seems to be ignored by Gmail provider?
https://wordpress.org/support/topic/bcc-for-gravity-forms/#post-9786927

## Expected Behavior

All emails should be sent to BCC if supported by an email delivery provider.
All providers should be examined.

## Steps to Reproduce (for bugs)

Using the plugin with Gravity Forms, and it does work well and sends the notifications to the email mentioned under the “TO” field, but not sending it to emails inside the “BCC” field.

**Comment by raajtram** [comment]
@slaFFik thanks for setting this up. Let me know if I can help in any way. Meanwhile, what do you think a temporary solution would be? The classic SMTP?

**Comment by slaFFik** [comment]
Classic SMTP might work (because it reuses the default `PHPMailer` class in WP core).

**Comment by raajtram** [comment]
Sounds good - thanks.

**Comment by robfrancken** [comment]
I also am having issues with BCC, Gmail, Gravity Forms. @slaFFik are you any closer to finding a solution?

**Comment by slaFFik** [comment]
Not yet, but it's on my radar and will be definitely fixed.
