### ISSUE TITLE
Empty sub menu item under dashboard menu linking to setup wizard

### ISSUE THREAD

**Issue by ezly123** [awesomemotive/WP-Mail-SMTP#90]
## Expected Behavior
No empty menu item should be shown.

## Current Behavior
An empty menu item is shown linking to /wp-admin/wp-mail-smtp-setup-wizard.

## Possible Solution
Get rid of the empty menu item.

## Steps to Reproduce
Not sure, but I've seen this on more than one of my sites using WP 5.4.x.

**Comment by capuderg** [comment]
Hi @ezly123,

thank you for reporting it. The issue was already fixed in code and the fix will be available in the next plugin update.

Have a nice day!
