### ISSUE TITLE
Proper support for EHLO

### ISSUE THREAD

**Issue by viniciusferrao** [awesomemotive/WP-Mail-SMTP#91]
## Expected Behavior
EHLO is being grabbed from the webserver name instead of manually being specified or fetched from the hostname of the machine.

## Current Behavior
We should have some control for EHLO since it may break MTAs that verifies EHLO.

## Possible Solution
https://wordpress.org/support/topic/ehlo-protocol-issue/

## Steps to Reproduce

1. Configure Other SMTP
2. Fail to deliver the messages due to wrong EHLO

## Side notes
I would like to know if the solution proposed on the link was already implemented or not. I wasn't able to found it on the code, nor there's an issue about this or there's anything on the recent changelogs for this bug fix.

**Comment by capuderg** [comment]
Hi @viniciusferrao,

for the majority of our users, the default process of retrieving the EHLO value (how PHPMailer bundled with WP core does it) will work just OK.

I think you belong to the more advanced category of users. And for these kinds of issues, we provide hooks (WP actions and filters) in our plugin, so advanced configuration can be done.

You can easily resolve your issue with the provided filter hook here: https://wordpress.org/support/topic/ehlo-protocol-issue/#post-13066427 and defining the EHLO value you need.

Have a nice day!

**Comment by viniciusferrao** [comment]
Thanks Greg!
