### ISSUE TITLE
Sending emails not working despite following instructions on Gmail setup

### ISSUE THREAD

**Issue by cbeardsley2000** [awesomemotive/wp-mail-smtp#92]
Here is the Debug code

Versions:
WordPress: 4.9.1
WordPress MS: No
PHP: 5.6.24-0+deb8u1
WP Mail SMTP: 1.1.0

PHPMailer:
Mailer: gmail

SMTP Debug:
[empty]

Any ideas?

1.1.0 Plugin version 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by cbeardsley2000** [comment]
P. S. It worked fine when I set it to my personal Gmail address but when I run the same procedure on my own domain email which has a Google account, it just won't send the email. Not even the test. In the steps, it doesn't mention the "add domain" step. Is this something I need to do to make it work, including the verification of the domain with GSC? Maybe this is where the process differs from an @gmail address to an @mydomain address with a separate Google account?

**Comment by slaFFik** [comment]
@cbeardsley2000

You can try to use the `develop` branch version of the plugin:
[wp-mail-smtp.zip](https://github.com/awesomemotive/wp-mail-smtp/files/1579018/wp-mail-smtp.zip)

It's not yet finalized, but should be stable enough to test. Also, it contains a ton of improvements into the providers debug output.

**Comment by slaFFik** [comment]
This issue doesn't relate to the plugin code/functionality, but more to a connection of your site to Gmail (something is blocking it). Thus, I'm closing this issue. But we can continue to communicate here in comments.

**Comment by cbeardsley2000** [comment]
Ok thanks. So there is no point me downloading the other plugin you mentioned?

**Comment by slaFFik** [comment]
No, there is a point. It can provide a hint of what is broken.

**Comment by cbeardsley2000** [comment]
Ah ok I will give it a try, thanks. What did you think about the domain thing I mentioned? Can it be neccessary to add the domain at that point?

**Comment by cbeardsley2000** [comment]
Also, the plugin you linked to earlier is the normal plugin I was already using. Is there a way to switch to the develop version or should it be a separate plugin?

**Comment by slaFFik** [comment]
@cbeardsley2000
Remove the version that is currently on your site.
Install the one from a zip in this message: https://github.com/awesomemotive/wp-mail-smtp/issues/92#issuecomment-353330053
