### ISSUE TITLE
Error 500 when there's error in Gmail SMTP

### ISSUE THREAD

**Issue by ethanchoi812** [awesomemotive/wp-mail-smtp#98]
When there's an error with set up in Gmail SMTP, test email will lead to error 500.

## Plugin version
1.2.1

## Current Behavior

When there's an error with set up in Gmail SMTP, test email will lead to error 500.

## Expected Behavior

User should see a debug message in case of error.

## Steps to Reproduce (for bugs)

1. Give wrong credentials in Gmail SMTP
2. Save settings
3. Test email

**Comment by slaFFik** [comment]
Might be related to #99.

**Comment by slaFFik** [comment]
fixed in #99.
